// mosques-data.js — Cami/mescid veri tabanı ve kullanıcı düzenlemelerinin (override) kalıcılığı

    // 1. BURSA TARİHİ CAMİ VE MESCİD VERİ TABANI
    let PRESET_MOSQUES = [
      { id: "ulu-cami", name: "Bursa Ulu Cami", district: "Osmangazi", address: "Nalbantoğlu, Atatürk Cd., Osmangazi/Bursa", mapsSearch: "Bursa Ulu Cami" },
      { id: "orhan-gazi", name: "Orhan Gazi Camii", district: "Osmangazi", address: "Nalbantoğlu, Tarihi Çarşı, Osmangazi/Bursa", mapsSearch: "Orhan Gazi Camii Bursa" },
      { id: "hudavendigar", name: "I. Murad Hüdavendigar Camii", district: "Osmangazi", address: "Çekirge, 1. Murat Sk., Osmangazi/Bursa", mapsSearch: "Hüdavendigar Camii Bursa" },
      { id: "muradiye", name: "Muradiye Camii (II. Murad)", district: "Osmangazi", address: "Muradiye, Prf. Dr. Halil İnalcık Sk., Osmangazi/Bursa", mapsSearch: "Muradiye Camii Bursa" },
      { id: "sehadet-camii", name: "Şahadet Camii (Hisar / Kale Camii)", district: "Osmangazi", address: "Hisar, Tophane Parkı İçi, Osmangazi/Bursa", mapsSearch: "Şahadet Camii Bursa" },
      { id: "uftade-camii", name: "Üftade Camii ve Mescidi", district: "Osmangazi", address: "Kavaklı, Üftade Sk., Osmangazi/Bursa", mapsSearch: "Üftade Camii Bursa" },
      { id: "yigit-kohne", name: "Yiğit Köhne Camii", district: "Osmangazi", address: "Alacahırka, Kiremitçi Sk., Osmangazi/Bursa", mapsSearch: "Yiğit Köhne Camii" },
      { id: "alaaddin-bey", name: "Alaaddin Bey Camii", district: "Osmangazi", address: "Alaaddin, Alaaddin Sk., Osmangazi/Bursa", mapsSearch: "Alaaddin Bey Camii Bursa" },
      { id: "abdal-camii", name: "Abdal Camii", district: "Osmangazi", address: "Abdal, Abdal Cd., Osmangazi/Bursa", mapsSearch: "Abdal Camii Bursa" },
      { id: "haci-ozbek", name: "Hacı Özbek Camii", district: "Osmangazi", address: "Reyhan, Tarihi Çarşı, Osmangazi/Bursa", mapsSearch: "Hacı Özbek Camii Bursa" },
      { id: "reyhan-camii", name: "Reyhan Camii", district: "Osmangazi", address: "Reyhan, Reyhan Cd., Osmangazi/Bursa", mapsSearch: "Reyhan Camii Bursa" },
      { id: "kavakli-camii", name: "Kavaklı Camii", district: "Osmangazi", address: "Kavaklı, Kavaklı Cd., Osmangazi/Bursa", mapsSearch: "Kavaklı Camii Bursa" },
      { id: "alacahirka-camii", name: "Alacahırka Camii", district: "Osmangazi", address: "Alacahırka, Alacahırka Cd., Osmangazi/Bursa", mapsSearch: "Alacahırka Camii Bursa" },
      { id: "sekerhoca-camii", name: "Şekerhoca Camii", district: "Osmangazi", address: "Şekerhoca, Şekerhoca Sk., Osmangazi/Bursa", mapsSearch: "Şekerhoca Camii Bursa" },
      { id: "karabas-i-veli", name: "Karabaş-i Veli Camii", district: "Osmangazi", address: "Maksem, Karabaş Sk., Osmangazi/Bursa", mapsSearch: "Karabaş-i Veli Kültür Merkezi" },
      { id: "tahtakale-camii", name: "Tahtakale Camii", district: "Osmangazi", address: "Tahtakale, Tahtakale Mh., Osmangazi/Bursa", mapsSearch: "Tahtakale Camii Bursa" },
      { id: "kiremitci-camii", name: "Kiremitçi Camii", district: "Osmangazi", address: "Kiremitçi, Kiremitçi Mh., Osmangazi/Bursa", mapsSearch: "Kiremitçi Camii Bursa" },
      { id: "kayhan-camii", name: "Kayhan Camii", district: "Osmangazi", address: "Kayhan, Kayhan Cd., Osmangazi/Bursa", mapsSearch: "Kayhan Camii Bursa" },
      { id: "tuzpazari-camii", name: "Tuzpazarı Camii", district: "Osmangazi", address: "Tuzpazarı, Çarşı İçi, Osmangazi/Bursa", mapsSearch: "Tuzpazarı Camii Bursa" },
      { id: "serefuddin-camii", name: "Şerefüddin Camii", district: "Osmangazi", address: "Hocaalizade, Şerefüddin Sk., Osmangazi/Bursa", mapsSearch: "Şerefüddin Camii" },
      { id: "hoca-alizade", name: "Hoca Alizade Camii", district: "Osmangazi", address: "Hocaalizade, Hocaalizade Cd., Osmangazi/Bursa", mapsSearch: "Hoca Alizade Camii Bursa" },
      { id: "veled-i-sarban", name: "Veled-i Sarban Camii", district: "Osmangazi", address: "Reyhan Mh., Sarban Sk., Osmangazi/Bursa", mapsSearch: "Veled-i Sarban Camii" },
      { id: "karaseyh-camii", name: "Karaşeyh Camii", district: "Osmangazi", address: "Karaşeyh Mh., Osmangazi/Bursa", mapsSearch: "Karaşeyh Camii Bursa" },
      { id: "seyh-muftu", name: "Şeyh Müftü Camii", district: "Osmangazi", address: "Şeyhmüftü Mh., Osmangazi/Bursa", mapsSearch: "Şeyh Müftü Camii" },
      { id: "somuncu-baba-firini", name: "Somuncu Baba Mescidi", district: "Osmangazi", address: "Mollafenari, Somuncu Baba Sk., Osmangazi/Bursa", mapsSearch: "Somuncu Baba Camii" },
      { id: "ishakpasa-camii", name: "İshakpaşa Camii", district: "Osmangazi", address: "Muradiye, İshakpaşa Sk., Osmangazi/Bursa", mapsSearch: "İshakpaşa Camii Bursa" },
      { id: "bedrettin-camii", name: "Bedrettin Camii", district: "Osmangazi", address: "Bedrettin Mh., Osmangazi/Bursa", mapsSearch: "Bedrettin Camii Bursa" },
      { id: "yerkapi-camii", name: "Yerkapı Camii", district: "Osmangazi", address: "Yerkapı Mh., Osmangazi/Bursa", mapsSearch: "Yerkapı Camii Bursa" },
      { id: "demirkapi-mescidi", name: "Demirkapı Mescidi", district: "Osmangazi", address: "Demirkapı Sk., Osmangazi/Bursa", mapsSearch: "Demirkapı Mescidi" },
      { id: "basci-ibrahim", name: "Başçı İbrahim Camii", district: "Osmangazi", address: "Maksem Mh., Başçı İbrahim Sk., Osmangazi/Bursa", mapsSearch: "Başçı İbrahim Camii" },
      { id: "sehrekustu-camii", name: "Şehreküstü Camii", district: "Osmangazi", address: "Şehreküstü, Osmangazi/Bursa", mapsSearch: "Şehreküstü Camii" },
      { id: "maksem-camii", name: "Maksem Camii", district: "Osmangazi", address: "Maksem, Osmangazi/Bursa", mapsSearch: "Maksem Camii" },
      { id: "dayioglu-camii", name: "Dayıoğlu Camii", district: "Osmangazi", address: "Tahtakale, Osmangazi/Bursa", mapsSearch: "Dayıoğlu Camii" },
      { id: "hamzabey-camii", name: "Hamzabey Camii", district: "Osmangazi", address: "Hamzabey Mh., Osmangazi/Bursa", mapsSearch: "Hamzabey Camii Bursa" },
      { id: "imaret-isabey", name: "İmaret-i İsabey Camii", district: "Osmangazi", address: "Alaaddin Mh., Kale içi, Osmangazi/Bursa", mapsSearch: "İmaret-i İsabey Camii Bursa" },
      { id: "nilufer-hidirlik", name: "Nilüfer Hatun (Hıdırlık) Camii", district: "Osmangazi", address: "Pınarbaşı Meydanı, İvaz Paşa Mh., Osmangazi/Bursa", mapsSearch: "Nilüfer Hatun Hıdırlık Camii Bursa" },
      { id: "armutkoy-camii", name: "Armutköy Camii", district: "Osmangazi", address: "Armutköy, Osmangazi/Bursa", mapsSearch: "Armutköy Camii Bursa" },
      { id: "yaylacik-camii", name: "Yaylacık Camii", district: "Osmangazi", address: "Yaylacık, Osmangazi/Bursa", mapsSearch: "Yaylacık Camii Bursa" },
      { id: "koza-hani-mescidi", name: "Koza Hanı Mescidi", district: "Osmangazi", address: "Şehreküstü, Uzun Çarşı Cd., Koza Hanı içi, Osmangazi/Bursa", mapsSearch: "Koza Hanı Mescidi Bursa" },
      { id: "haci-ivaz-pasa-camii", name: "Hacı İvaz Paşa Camii", district: "Osmangazi", address: "Tavuk Pazarı, Pirinç Hanı karşısı, Osmangazi/Bursa", mapsSearch: "Hacı İvaz Paşa Camii Bursa" },
      { id: "hatice-isfendiyar-sultan-camii", name: "Hatice İsfendiyar Sultan Camii", district: "Osmangazi", address: "Gökdere, Kamberler Mahallesi, Osmangazi/Bursa", mapsSearch: "Hatice İsfendiyar Sultan Camii Bursa" },
      { id: "gazi-timurtas-pasa-camii", name: "Gazi Timurtaş Paşa Camii", district: "Osmangazi", address: "Demirtaş Mahallesi, Osmangazi/Bursa", mapsSearch: "Timurtaş Paşa Camii Bursa" },
      { id: "azeb-bey-camii", name: "Azeb Bey Camii", district: "Osmangazi", address: "Muradiye, Kullukçu Sk., Osmangazi/Bursa", mapsSearch: "Azeb Bey Camii Bursa" },
      { id: "ahmed-dai-camii", name: "Ahmed Dai Camii", district: "Osmangazi", address: "Cumhuriyet Cd. ile Ahmed Dai Sk. kesişimi, Osmangazi/Bursa", mapsSearch: "Ahmed Dai Camii Bursa" },
      { id: "yesil-cami", name: "Yeşil Cami", district: "Yıldırım", address: "Yeşil, Yıldırım/Bursa", mapsSearch: "Yeşil Cami Bursa" },
      { id: "emir-sultan", name: "Emir Sultan Camii", district: "Yıldırım", address: "Emirsultan, Yıldırım/Bursa", mapsSearch: "Emir Sultan Camii Bursa" },
      { id: "yildirim-bayezid", name: "Yıldırım Bayezid Camii", district: "Yıldırım", address: "Yıldırım, Yıldırım/Bursa", mapsSearch: "Yıldırım Bayezid Camii" },
      { id: "ali-pasa", name: "Ali Paşa Camii", district: "Yıldırım", address: "Namazgah, Ali Paşa Sk., Yıldırım/Bursa", mapsSearch: "Ali Paşa Camii Bursa" },
      { id: "namazgah", name: "Bursa Tarihi Namazgah", district: "Yıldırım", address: "Namazgah, Yıldırım/Bursa", mapsSearch: "Namazgah Bursa" },
      { id: "molla-yegan", name: "Molla Yegan Camii", district: "Yıldırım", address: "Yıldırım Mh., Yıldırım/Bursa", mapsSearch: "Molla Yegan" },
      { id: "davutkadi-camii", name: "Davutkadı Camii", district: "Yıldırım", address: "Davutkadı Mh., Yıldırım/Bursa", mapsSearch: "Davutkadı Camii Bursa" },
      { id: "musababa-camii", name: "Musababa Camii", district: "Yıldırım", address: "Musababa Mh., Yıldırım/Bursa", mapsSearch: "Musababa Camii" },
      { id: "piremir-camii", name: "Piremir Camii", district: "Yıldırım", address: "Piremir Mh., Yıldırım/Bursa", mapsSearch: "Piremir Camii" },
      { id: "teferruc-camii", name: "Teferrüç Camii", district: "Yıldırım", address: "Teferrüç, Yıldırım/Bursa", mapsSearch: "Teferrüç Camii" },
      { id: "karaagac-camii", name: "Karaağaç Camii", district: "Yıldırım", address: "Karaağaç Mh., Yıldırım/Bursa", mapsSearch: "Karaağaç Camii" },
      { id: "zeyniler-camii", name: "Zeyniler Köyü Mescidi", district: "Yıldırım", address: "Zeyniler Köyü, Yıldırım/Bursa", mapsSearch: "Zeyniler Mescidi" },
      { id: "molla-arap", name: "Molla Arap Camii", district: "Yıldırım", address: "Mollaarap Mh., Yıldırım/Bursa", mapsSearch: "Molla Arap Camii" },
      { id: "umurbey-camii", name: "Umurbey Camii", district: "Yıldırım", address: "Umurbey Mh., Yıldırım/Bursa", mapsSearch: "Umurbey Camii" },
      { id: "yesil-mescidi", name: "Yeşil Türbe Mescidi", district: "Yıldırım", address: "Yeşil, Yıldırım/Bursa", mapsSearch: "Yeşil Türbe" },
      { id: "selcuk-hatun", name: "Selçuk Hatun Camii", district: "Yıldırım", address: "Selçuk Hatun Mh., Yıldırım/Bursa", mapsSearch: "Selçuk Hatun Camii" },
      { id: "haci-ilyas-camii", name: "Hacı İlyas Camii", district: "Yıldırım", address: "Hacı İlyas Mh., Yıldırım/Bursa", mapsSearch: "Hacı İlyas Camii" },
      { id: "degirmenlikizik-camii", name: "Değirmenlikızık Camii", district: "Yıldırım", address: "Değirmenlikızık, Yıldırım/Bursa", mapsSearch: "Değirmenlikızık Camii" },
      { id: "fidyekizik-camii", name: "Fidyekızık Tarihi Camii", district: "Yıldırım", address: "Fidyekızık, Yıldırım/Bursa", mapsSearch: "Fidyekızık Camii" },
      { id: "sitti-hatun", name: "Sitti Hatun Mescidi", district: "Yıldırım", address: "Umurbey, Yıldırım/Bursa", mapsSearch: "Sitti Hatun Camii" },
      { id: "hamamlikizik-camii", name: "Hamamlıkızık Camii", district: "Yıldırım", address: "Hamamlıkızık Köyü, Yıldırım/Bursa", mapsSearch: "Hamamlıkızık Camii" },
      { id: "cumalikizik-camii", name: "Cumalıkızık Camii", district: "Yıldırım", address: "Cumalıkızık Köyü, Yıldırım/Bursa", mapsSearch: "Cumalıkızık Camii" },
      { id: "bayezid-pasa-catal", name: "Bayezid Paşa (Çatal Mescit) Camii", district: "Yıldırım", address: "Yıldırım/Bursa", mapsSearch: "Bayezid Paşa Camii Bursa Çatal Mescit" },
      { id: "meydancik-camii", name: "Meydancık Camii", district: "Yıldırım", address: "Meydancık, Alancık Sk., Yıldırım/Bursa", mapsSearch: "Meydancık Camii Bursa" },
      { id: "iznik-ayasofya", name: "İznik Ayasofya Orhan Camii", district: "İznik", address: "İznik Merkez, İznik/Bursa", mapsSearch: "İznik Ayasofya Camii" },
      { id: "iznik-yesil", name: "İznik Yeşil Camii", district: "İznik", address: "Lefke Kapı civarı, İznik/Bursa", mapsSearch: "İznik Yeşil Camii" },
      { id: "haci-ozbek-iznik", name: "Hacı Özbek Camii (Çarşı Mescidi)", district: "İznik", address: "Çarşı İçi, İznik/Bursa", mapsSearch: "Hacı Özbek Camii İznik" },
      { id: "mahmut-celebi", name: "Mahmut Çelebi Camii", district: "İznik", address: "Ayasofya civarı, İznik/Bursa", mapsSearch: "Mahmut Çelebi Camii İznik" },
      { id: "esrefzade", name: "Eşrefzade (Eşref-i Rumi) Camii", district: "İznik", address: "İznik Merkez, İznik/Bursa", mapsSearch: "Eşrefzade Camii İznik" },
      { id: "seyh-kutbuddin", name: "Şeyh Kutbuddin Camii", district: "İznik", address: "İznik, Bursa", mapsSearch: "Şeyh Kutbuddin Camii İznik" },
      { id: "yakup-celebi-iznik", name: "Yakup Çelebi Camii", district: "İznik", address: "İznik Merkez, İznik/Bursa", mapsSearch: "Yakup Çelebi Camii İznik", addedAt: "2026-07-13" },
      { id: "orhan-gazi-eski-cami-iznik", name: "Orhan Gazi Eski Camisi", district: "İznik", address: "Yenişehir Kapısı dışı, Kırgızlar Türbesi karşısı, İznik/Bursa", mapsSearch: "Orhan Gazi Camii İznik", addedAt: "2026-07-13T01:00:00" },
      { id: "tirilye-fatih-camii", name: "Tirilye Fatih Camii (Hagios Stephanos Kilisesi)", district: "Mudanya", address: "Tirilye, Mudanya/Bursa", mapsSearch: "Fatih Camii Tirilye Mudanya", addedAt: "2026-07-13T02:00:00" },
      { id: "halil-aga-eski", name: "Halil Ağa Camii (Eski Cami)", district: "Mudanya", address: "Hasanbey, Mudanya/Bursa", mapsSearch: "Halil Ağa Camii Mudanya" },
      { id: "hasan-bey-camii-mudanya", name: "Hasan Bey Camii", district: "Mudanya", address: "Hasanbey Mahallesi, Mudanya/Bursa", mapsSearch: "Hasan Bey Camii Mudanya", addedAt: "2026-07-13T05:00:00" },
      { id: "omer-bey-camii-mudanya", name: "Ömer Bey Camii", district: "Mudanya", address: "Ömerbey Mahallesi, Halitpaşa Cd. No:72B, Mudanya/Bursa", mapsSearch: "Ömer Bey Camii Mudanya", addedAt: "2026-07-13T04:00:00" },
      { id: "tekke-i-cedidi-camii", name: "Tekke-i Cedidi Camii", district: "Mudanya", address: "Mudanya Merkez, Mudanya/Bursa", mapsSearch: "Tekke-i Cedidi Camii Mudanya", addedAt: "2026-07-13T03:00:00" },
      { id: "tekke-i-atik", name: "Tekke-i Atik Camii", district: "Mudanya", address: "Hasanbey, Mudanya/Bursa", mapsSearch: "Tekke-i Atik Camii Mudanya" },
      { id: "kursunlu-camii", name: "Kurşunlu Camii", district: "Gemlik", address: "Kurşunlu, Gemlik/Bursa", mapsSearch: "Kurşunlu Camii Gemlik" },
      { id: "umurbey-carsi-camii", name: "Umurbey Çarşı Camii", district: "Gemlik", address: "Umurbey Beldesi Merkez, Çarşı içi, Gemlik/Bursa", mapsSearch: "Umurbey Çarşı Camii Gemlik" },
      { id: "inegol-ishakpasa", name: "İshakpaşa Camii", district: "İnegöl", address: "İnegöl Merkez, İnegöl/Bursa", mapsSearch: "İshakpaşa Camii İnegöl" },
      { id: "yildirim-camii-inegol", name: "Yıldırım Camii", district: "İnegöl", address: "Cuma Mahallesi, Nuri Doğrul Cd., İshak Paşa Medresesi yanı, İnegöl/Bursa", mapsSearch: "Yıldırım Camii İnegöl", addedAt: "2026-07-13T06:00:00" },
      { id: "yenisehir-ulu", name: "Orhan Gazi Ulu Camii", district: "Yenişehir", address: "Ulucami Mahallesi, Ulucami Sokak, Yenişehir/Bursa", mapsSearch: "Yenişehir Ulu Camii" },
      { id: "yarhisar-orhan-gazi-camii", name: "Yarhisar Orhan Gazi Camii (Nilüfer Hatun Camii)", district: "Yenişehir", address: "Yarhisar Köyü, Yenişehir/Bursa", mapsSearch: "Orhan Gazi Camii Yarhisar Yenişehir Bursa", addedAt: "2026-07-13T11:00:00" },
      { id: "bali-bey-camii-yenisehir", name: "Balı Bey Camii", district: "Yenişehir", address: "Yenişehir Merkez, Yenişehir/Bursa", mapsSearch: "Balı Bey Camii Yenişehir", addedAt: "2026-07-13T07:00:00" },
      { id: "kumluk-camii-yenisehir", name: "Kumluk Camii", district: "Yenişehir", address: "Murat Paşa Mahallesi, Yenişehir/Bursa", mapsSearch: "Kumluk Camii Yenişehir Bursa", addedAt: "2026-07-13T08:00:00" },
      { id: "voyvoda-cinarli-camii-yenisehir", name: "Voyvoda (Çınarlı) Camii", district: "Yenişehir", address: "Bali Bey Camii ve Külliyesi yakını (kuzeyi), Yenişehir/Bursa", mapsSearch: "Çınarlı Camii Yenişehir Bursa", addedAt: "2026-07-13T09:00:00" },
      { id: "sinan-pasa-camii-kulliyesi-yenisehir", name: "Sinan Paşa Camii ve Külliyesi (Kurşunlu Han)", district: "Yenişehir", address: "Yenişehir Merkez, Yenişehir/Bursa", mapsSearch: "Sinan Paşa Külliyesi Yenişehir Bursa", addedAt: "2026-07-13T10:00:00" },
      { id: "mustafakemalpasa-yesil-camii", name: "Yeşil Camii", district: "Mustafakemalpaşa", address: "Çırpan Mahallesi, Yeşil Cami Sk. No:1, Mustafakemalpaşa/Bursa", mapsSearch: "Yeşil Camii Mustafakemalpaşa" },
      { id: "mustafakemalpasa-yenickoy-camii", name: "Yeniceköy Camii", district: "Mustafakemalpaşa", address: "Yenice Köyü, Devecikonağı, Mustafakemalpaşa/Bursa", mapsSearch: "Yeniceköy Camii Mustafakemalpaşa" },
      { id: "mustafakemalpasa-muftu-camii", name: "Müftü Camii", district: "Mustafakemalpaşa", address: "Şeyhmüftü Mahallesi, Balıkesir Cd., Mustafakemalpaşa/Bursa", mapsSearch: "Müftü Camii Mustafakemalpaşa" },
      { id: "mustafakemalpasa-melikkoyu-camii", name: "Melik Köyü Camii", district: "Mustafakemalpaşa", address: "Melik Köyü, Mustafakemalpaşa/Bursa", mapsSearch: "Melik Köyü Camii Mustafakemalpaşa" },
      { id: "mustafakemalpasa-lala-sahin-pasa-kulliyesi", name: "Lala Şahin Paşa Külliyesi (Cami, Medrese, Türbe)", district: "Mustafakemalpaşa", address: "Kirmasti Çayı kıyısındaki park, Mustafakemalpaşa/Bursa", mapsSearch: "Lala Şahin Paşa Türbesi Mustafakemalpaşa" },
      { id: "mustafakemalpasa-kestelek-koyu-camii", name: "Kestelek Köyü Camii", district: "Mustafakemalpaşa", address: "Kestelek Köyü, Çaltılıbük, Mustafakemalpaşa/Bursa", mapsSearch: "Kestelek Köyü Camii Mustafakemalpaşa" },
      { id: "mustafakemalpasa-hamzabey-camii", name: "Hamzabey Camii", district: "Mustafakemalpaşa", address: "Mustafakemalpaşa/Bursa", mapsSearch: "Hamzabey Camii Mustafakemalpaşa" },
      { id: "mustafakemalpasa-seydiali-koyu-camii", name: "Seydi Ali Köyü Camisi", district: "Mustafakemalpaşa", address: "Seydi Ali Köyü, Mustafakemalpaşa/Bursa", mapsSearch: "Seydi Ali Köyü Camisi Mustafakemalpaşa" },
      { id: "mustafakemalpasa-ayaz-koyu-camii", name: "Ayaz Köyü Camisi", district: "Mustafakemalpaşa", address: "Ayaz Köyü, Mustafakemalpaşa/Bursa", mapsSearch: "Ayaz Köyü Camisi Mustafakemalpaşa" },
      { id: "golyazi-eski-camii", name: "Gölyazı Eski Camii", district: "Nilüfer", address: "Gölyazı, Nilüfer/Bursa", mapsSearch: "Gölyazı Eski Camii Bursa" },
      { id: "karacabey-yenisaribeykoyu-camii", name: "Yenisarıbey Köyü Camii", district: "Karacabey", address: "Yenisarıbey Köyü, Karacabey/Bursa", mapsSearch: "Yenisarıbey Köyü Camii Karacabey" },
      { id: "karacabey-kumbetli-camii", name: "Kümbetli Cami", district: "Karacabey", address: "Hamidiye Mahallesi, Karacabey/Bursa", mapsSearch: "Kümbetli Cami Karacabey" },
      { id: "karacabey-ismetpasa-haci-ali-aga-camii", name: "Hacı Ali Ağa Camii", district: "Karacabey", address: "İsmetpaşa Köyü, Karacabey/Bursa", mapsSearch: "Hacı Ali Ağa Camii İsmetpaşa Karacabey" },
      { id: "karacabey-uluabat-eski-valide-sultan-camii", name: "Uluabat Eski (Valide Sultan) Camii", district: "Karacabey", address: "Uluabat Köyü, Karacabey/Bursa", mapsSearch: "Uluabat Eski Cami Karacabey" },
      { id: "karacabey-imaret-kursunlu-camii", name: "İmaret Camii (Kurşunlu Cami)", district: "Karacabey", address: "Selimiye Mahallesi, Karacabey/Bursa", mapsSearch: "İmaret Camii Kurşunlu Cami Karacabey" },
      { id: "karacabey-ulu-camii", name: "Ulu Cami", district: "Karacabey", address: "Eski Karacabey, Karacabey/Bursa", mapsSearch: "Ulu Cami Karacabey" }
    ];
    // 1b. CAMİ TARİHÇE / DETAY BİLGİSİ VERİ TABANI (yapılış tarihi, banisi, kısa bilgi notu)
    const MOSQUE_INFO = {
      "ulu-cami": { period: "1396 – 1399 (Yıldırım Bayezid Dönemi)", founder: "Yıldırım Bayezid (I. Bayezid)", architect: "Mimarı kesin olarak bilinmiyor; kaynaklarda Ali Neccar adı geçer.", info: "Niğbolu Zaferi sonrası, adak olarak 20 ayrı cami yerine 20 kubbeli tek bir ulu cami yapılması önerisiyle inşa edilmiştir. Türkiye'nin iç mekânı en geniş camisi olup kündekari tekniğiyle işlenmiş tarihi minberi ve içindeki şadırvanla ünlüdür." },
      "orhan-gazi": { period: "1339 (Orhan Gazi Dönemi)", founder: "Orhan Gazi", info: "Bursa'da kale surları dışına inşa edilen ilk külliyenin ana yapısıdır; şehirdeki 'zaviyeli plan' tipindeki ilk camidir. 1413'te Karamanoğlu Mehmed Bey tarafından tahrip edilmiş, 1417'de Çelebi Mehmed tarafından onarılmıştır." },
      "hudavendigar": { period: "1365 – 1366 (I. Murad Dönemi)", founder: "I. Murad (Hüdavendigar)", info: "Alt katı ibadet mekânı, üst katı medrese olarak tasarlanmış; Osmanlı mimarisinde eşi görülmeyen iki katlı bir yapıdır. O dönem şehre uzak sayılan Çekirge'de, ovaya hâkim bir tepe üzerine inşa edilmiştir." },
      "muradiye": { period: "1425 – 1426 (II. Murad Dönemi)", founder: "II. Murad", info: "Bursa'da bir Osmanlı padişahı adına yapılan son camidir. Kündekari tekniğiyle işlenmiş ahşap giriş kapısı ve İznik çinileriyle tanınır; külliye çevresinde çok sayıda şehzade ve saray mensubunun türbesi bulunur." },
      "sehadet-camii": { period: "1365 (I. Murad Hüdavendigar Dönemi); 1892'de büyük ölçüde yenilendi", founder: "I. Murad (Hüdavendigar)", info: "Hisar içinde, sarayın tam karşısında I. Murad Hüdavendigar tarafından 1365 yılında 'Sultan Camisi' (Kale Camisi) adıyla yaptırılmıştır. Çeşitli kaynaklara göre, Sultan'ın 1389'da Kosova'da şehit düşmesi üzerine cami 'Şahadet Camisi' adını almıştır. Üç sahınlı; orta sahın iki kubbe, iki yan sahın ise ikişerden toplam dört tonozla örtülü, çok direkli-kubbeli bir Ulu Cami örneğidir. Kuzeydoğusunda tek minaresi, kuzeyinde dört küçük kubbeli son cemaat yeri bulunur; 17. yüzyılda güney cephesini desteklemek için iki payanda eklenmiştir. 1855 depreminde ağır hasar görmüş, 1892'de Vali Mahmud Celaleddin tarafından yıkıntılar üzerine, yalnızca orta sahından ibaret ve aslının yaklaşık üçte iki küçüklüğünde, oldukça farklı bir biçimde yeniden inşa edilmiştir. Cephesi 19. yüzyılda Avrupa'da yaygın Gotik üslupta, sivri kemerli pencerelerle yapılmıştır. Kaynak: turkiyenintarihieserleri.com" },
      "yesil-cami": { period: "1414 – 1419 (Çelebi Mehmed Dönemi)", founder: "Çelebi Sultan I. Mehmed", architect: "Hacı İvaz Paşa", info: "Fetret Devri sonrası devletin yeniden toparlanışını simgeleyen yapıdır. Marmara Adası mermeri ve zengin İznik çinileriyle erken dönem Osmanlı sanatının en görkemli örneklerinden sayılır; karşısındaki Yeşil Türbe'de banisi Çelebi Mehmed medfundur." },
      "emir-sultan": { period: "15. yüzyıl başı (Çelebi Mehmed / II. Murad Dönemi)", founder: "Hundi Fatma Hatun (Yıldırım Bayezid'in kızı, Emir Sultan'ın eşi)", info: "Buhara asıllı âlim Emir Sultan adına eşi tarafından yaptırılmıştır. 1795 depreminde tamamen yıkılmış, 1804'te III. Selim tarafından aynı plan üzerine yeniden inşa edilmiştir. Avlusundaki asırlık çınarlar ve Emir Sultan Türbesi'yle bilinir." },
      "yildirim-bayezid": { period: "1391 – 1395 (Yıldırım Bayezid Dönemi)", founder: "Yıldırım Bayezid (I. Bayezid)", info: "'Ters T' planlı erken dönem Osmanlı camilerindendir; tamamen kesme taştan inşa edilmesi ve ünlü 'Bursa kemeri'nin ilk kez burada kullanılmasıyla dikkat çeker. 1855 depreminden sonra kapsamlı onarım görmüştür." },
      "ali-pasa": { period: "14. yüzyıl sonu (Yıldırım Bayezid Dönemi)", founder: "Çandarlı Ali Paşa (Yıldırım Bayezid'in veziri)", info: "Orhan Gazi Camii ile başlayan 'kanatlı, ters T planlı zaviyeli camiler' grubundandır. 1855 Bursa depreminde hasar görmüş ve sonrasında onarılmıştır." },
      "alaaddin-bey": { period: "1326 (Orhan Gazi Dönemi)", founder: "Alaaddin Bey (Osman Gazi'nin oğlu)", info: "Bursa'nın fethinin hemen ardından yaptırılan, şehrin ilk camisi olarak kabul edilir. Tuğla örgülü minaresi ve sade avlusuyla erken dönem Osmanlı mimarisinin ilk izlerini taşır." },
      "serefuddin-camii": { period: "1479 (II. Murad / Fatih Dönemi)", founder: "Şerafeddin Paşa", info: "Okçular Çarşısı içinde yer aldığı için halk arasında 'Okçular Camii' olarak da bilinir. Kare planlı, tek kubbeli, sade bir mahalle camisidir." },
      "uftade-camii": { period: "16. yüzyılın ikinci yarısı (Kanuni / II. Selim Dönemi)", founder: "Üftade Hazretleri (Mehmed Muhyiddin Üftade)", info: "Aziz Mahmud Hüdayi'nin hocası olan meşhur mutasavvıf Üftade Hazretleri tarafından yaptırılmıştır. Cami çeşitli depremlerde hasar görmüş, torunu İbrahim ve sonraki dönemde Rıza Paşa tarafından onarılmıştır; karşısındaki türbede Üftade Hazretleri medfundur." },
      "karabas-i-veli": { period: "16. yüzyıl", founder: "Yakup Çelebi", info: "Aslen bir Mevlevi tekkesi olarak inşa edilmiş, adını burada uzun yıllar irşad faaliyeti yürüten Karabaş-i Veli Hazretleri'nden almıştır. Günümüzde ibadetin yanı sıra kültür merkezi olarak da kullanılmaktadır." },
      "iznik-ayasofya": { period: "1331 (Orhan Gazi Dönemi) — aslen Bizans bazilikası", founder: "Orhan Gazi (camiye dönüştüren)", info: "MS 7. yüzyılda inşa edilen basilikadan dönüştürülmüştür. 1331'de İznik'in fethiyle Orhan Gazi tarafından camiye çevrilmiştir. 2. Ekümenik Konsil'in (787) yapıldığı yer olarak Hristiyanlık tarihinde de büyük öneme sahiptir. Günümüzde ibadete açıktır." },
      "iznik-yesil": { period: "1378'de başlandı, 1387'de tamamlandı", founder: "Çandarlı Kara Halil Hayreddin Paşa (başlatan), Vezir-i Azam Ali Paşa (bitiren)", architect: "Hacı b. Musa", info: "İznik'in abidelerle dolu çevresinde, Lefke Kapısı civarında yer alan caminin en dikkat çekici eseridir. Evliya Çelebi de bu camiden Hayreddin Paşa Camii, yani Yeşil Camii adıyla şöhret bulmuş güzel bir cami olarak söz eder. Tek kubbeli ve revaklı sade bir yapı olmasına rağmen büyük bir etki bırakır; bu etkide malzeme, işçilik ve zengin süslemenin yanında, camiye adını veren yeşil bir sütun gibi yükselen zarif minarenin ve harime eklenen üçlü kemerli revakın getirdiği ferahlığın büyük payı vardır. Çandarlı Kara Halil Hayreddin Paşa tarafından 1378'de başlanan yapı, 1387'de Vezir-i Azam Ali Paşa tarafından tamamlanmıştır; kitabeye göre mimarı Hacı b. Musa'dır. Zengin mermer işçiliğine sahip son cemaat yerinin orta bölümü küçük zarif bir kubbeyle örtülüdür; sütun başlıkları, pencere alınlık ve çerçeveleri, kapı çevresi ve mihrap mermerin dantel gibi işlenmesiyle bezenmiştir. Uzunlamasına dikdörtgen ana mekânın giriş kısmında sütunlarla ayrılan, ortasında küçük bir kubbenin yükseldiği bir bölüm bulunur; asıl mekânı ise 10,5 metre çapında, kurşun kaplı büyük bir kubbe örter. Caminin en güzel unsuru minaresidir: yuvarlak gövdeli minarede alttaki bir sıra stalaktitin ardından beyaz mermer bir kuşak, sonrasında ise çini süsleme başlar — mermer üzerinde büyük altı köşeli yıldızların arasına küçük sekiz köşeliler ustalıkla yerleştirilerek ikinci bir kuşak oluşturulmuş, gövde sırlı tuğla zemin üzerine mavi-beyaz çinilerle zikzak desenlerle süslenmiş, üstüne dört sıra çiniyle stalaktitli bir şerefe yapılmıştır. Yunanlıların verdiği tahribat nedeniyle cami 1956-1968 yılları arasında restore edilmiştir." },
      "haci-ozbek-iznik": { period: "734 (1333-34), fetihten iki üç yıl sonra (Orhan Gazi Dönemi)", founder: "Hacı Özbek b. Mehmed", info: "Lefkekapısı'na giden ana caddede, Eşrefoğlu Rûmî Külliyesi hizasında yer alır. Üç satırlık kitabesiyle kitabesi mevcut en eski Osmanlı eseri kabul edilir; aslında bir Bizans kilisesi olduğu yönündeki iddia ise vaktiyle İznik Rumları'nca uydurulmuş asılsız bir söylentidir. Kare planlı, iç ölçüleri yaklaşık 7,50 m olan yapı, taş ile tuğla hatıllardan karma malzemeyle inşa edilmiş; kemerlerde küfeki taşı aralarına üç tuğla konulan örgü kullanılması, yapımında yerli Bizanslı duvarcı ustaların çalıştığını gösterir. İlk yapıldığında iki mermer sütuna dayanan, üç kemerle dışa açılan özgün bir son cemaat yeri bulunuyordu; ancak cadde genişletme gerekçesiyle 1930'lu yıllarda bu bölüm yıktırılmış, caminin başka bir cephesine uydurma bir son cemaat yeri eklenmiştir. Kiremit örtülü kubbe, eskiden dört pencereli iken sonradan çoğu kapatılan on iki köşeli bir kasnağa oturur; kareden kasnağa geçiş Türk baklavalarıyla sağlanmıştır. Kapıya göre ana eksende olmayan mihrap özgün biçimini kaybetmiş, kitabesi de yerinden sökülerek mihrabın sağındaki pencereye yerleştirilmiştir. Bitişiğindeki çeşmeden günümüze bir iz kalmamıştır. Kurtuluş Savaşı döneminde Rumların Türk eserlerine yönelik tahribatını atlatabilen yapı, sonraki dönemde özgün duvar tekniğine uygun şekilde restore edilmeyişi nedeniyle tarihi değerine uygun bir görünüme kavuşamamıştır. Kaynak: İslam Ansiklopedisi" },
      "yakup-celebi-iznik": { period: "791 (1389) yılından önce (I. Murad Dönemi)", founder: "Yâkub Çelebi (Sultan I. Murad'ın oğlu)", info: "Zâviyeli/tabhâneli plan grubundan olan yapı, bir sıra kesme taş - üç sıra tuğla almaşık duvar örgüsüne, kirpi saçaklı kubbe ve tonozlara sahiptir. Önünde beş birimli, aynalı tonozlu bir revak; içeride ortada kubbeli sofa mekânı, iki yanında ise ocaklı tabhâne odaları bulunur. Mihrap bölümü daha yüksek bir kubbeyle örtülü olup mihrap ve minber 1963 onarımında yenilenmiştir. Yapının önünde, Yâkub Çelebi için inşa edilmiş kare planlı açık bir türbe yer alır; Çelebi Bursa'da babasının türbesine defnedildiğinden bu yapı makam türbesi niteliğindedir. Cami 1919'a kadar kullanılmış, 1934'te müze deposuna çevrilmiş, 1963'te onarılarak yeniden ibadete açılmış ve yakın zamanda esaslı bir onarım daha görmüştür. Kaynak: İslam Ansiklopedisi" },
      "orhan-gazi-eski-cami-iznik": { period: "1325-1326 dolayı (Osmanlı fethinden en az beş yıl önce, Orhan Gazi Dönemi, salt. 1326-1362)", founder: "Orhan Gazi", info: "İznik ilçe merkezinde, Yenişehir Kapısı dışında ve Kırgızlar Türbesi karşısında bulunan yapı, günümüzde tümüyle harap durumda bir cami kalıntısıdır. Yıkıntı halindeyken 1963 yılında Prof. Oktay Aslanapa'nın yönettiği kazıyla gün yüzüne çıkarılmıştır. Beden duvarları moloz taş örgülü ve oldukça ince olup çatı ile örtülü olduğu hemen hemen kesinleşmiştir. Asıl ibadet mekânı, 18 santimetre boyunda altı köşeli çinilerle süslenmiştir; bu çiniler renk bakımından güzel olmakla birlikte işlenme yöntemleri ilkeldir. Mihrabın çevresinde ve kapı dolaylarında, ince ve gelişmiş bir işçiliğin izlerini taşıyan alçı süsleme kalıntıları bulunmaktadır. Camiden elde edilen buluntular ve bir bölümü kırık yazıt taşı İznik Müzesi'nde sergilenmektedir. Kaynak: İslam Ansiklopedisi" },
      "mahmut-celebi": { period: "1442-1443 (II. Murad Dönemi)", founder: "Vezir Mahmut Çelebi (II. Murad'ın kayınbiraderi, Çandarlı Halil Paşa'nın torunu)", info: "İznik Mahmut Çelebi Mahallesi'nde, Ayasofya'nın yaklaşık 100 m güneyinde yer alır. Erken Osmanlı devri tek kubbeli camiler grubundandır; kuzeyinde dikdörtgen planlı, üzeri tonoz örtülü ve ortası kubbeli bir son cemaat yeri bulunur. Giriş kapısı üzerinde 45x180 cm ölçüsünde üç satırlık yapım kitabesi vardır. Yeşil Cami'nin küçük bir örneği sayılan yapının üzeri duvarlara dayanan bir kubbeyle örtülü olup kareden kubbeye geçiş Türk üçgenli bir frizle sağlanmıştır. Minaresi yeşil sırlı tuğlalardan kuşaklarla çevrili olup 1967 depreminde zarar görmüştür. Mahmut Çelebi, caminin bahçesindeki demir parmaklıklı bir türbede medfundur. Karşısındaki İznik'in en eski çeşmesi 1970'li yıllarda yıkılmış, yanındaki aşhane-imaretten ise yalnızca duvar izleri günümüze ulaşabilmiştir. Kaynak: e-tarih.org" },
      "esrefzade": { period: "15. yüzyıl sonu, 1485'ten önce (Eşrefoğlu Rûmî'nin ölümünden sonra yapıldığı tahmin edilir)", founder: "Bânisi kesin olarak bilinmemektedir; Eşrefoğlu Rûmî (ö. 874/1469-70) adına inşa edilmiştir", info: "Eşrefzâde veya Eşref-i Rûmî Camii adlarıyla da anılır; Kādiriyye tarikatının Eşrefiyye kolunun kurucusu Eşrefoğlu Rûmî adına yaptırılmıştır. Yunan işgali sırasında tamamen yıkılmış, özgün yapıdan günümüze yalnızca minare ile hazire kısmı ulaşabilmiştir. İnşa tarihi kesin olmamakla birlikte, 1485'te Fatih Sultan Mehmed'in eşi Mükrime Hatun'un burada bir cüz okuma vakfı kurmuş olması yapının bu tarihten önce var olduğunu göstermektedir. Eski fotoğraflardan, uzunlamasına dikdörtgen planlı, düz çatılı caminin dört sütuna oturan beş kemerli derin bir son cemaat yerine sahip olduğu, mukarnaslı kavsarası dışında bütünüyle çini kaplı bir mihrabının bulunduğu anlaşılmaktadır. Camiden ayrı, türbe duvarına bitişik konumdaki tuğla gövdeli minare, IV. Murad döneminde yapılan onarımda zengin çini kuşaklarla süslenmiş; bu onarımda cami ve bitişiğindeki türbenin içi de çinilerle kaplanmıştır. Söz konusu çinilerden günümüze ulaşan parçalar İznik Müzesi'nde sergilenmekte olup İznik çiniciliğinin XVII. yüzyıldaki son dönem örnekleri arasında değerli kabul edilir; caminin, İznik'te üretilip yerinde kullanılan tek çinili eser olması ayrıca önemlidir. Yapı çevresinde vaktiyle Eşrefoğlu Rûmî'nin büyük türbesi, şadırvanlı bir avlu, küçük bir hamam ve geniş bir tekke kompleksinin izleri bulunuyordu; bu da yapının bir külliye olarak zamanla genişletildiğini düşündürmektedir. Tamamen harap olan cami, 1954 yılında cami derneği tarafından sade bir kâgir yapı olarak yeniden inşa edilip aynı yıl ibadete açılmış, günümüzde de kullanılmaktadır; Eşrefoğlu Rûmî'ye ve yakınlarına ait bazı kabirler minare ile caminin sağ tarafı arasındaki açık hazirede yer almaktadır. Kaynak: İslam Ansiklopedisi" },
      "tirilye-fatih-camii": { period: "610-850 arası (asıl kilise yapımı); 968/1560 (camiye çevrilişi, Kanuni Dönemi)", founder: "Aslen bir Bizans kilisesi; 16. yüzyılda Osmanlılar tarafından satın alınarak camiye çevrilmiştir", info: "Tirilye'deki Hagios Stephanos (ilk adıyla Aya Todori, ayrıca Kenolakkus Manastırı Kilisesi olarak da bilinen) kilisesi, Güney Marmara'daki en eski ve özgün Bizans kiliselerinden biridir ve 610-850 yılları arasına tarihlenen ender Bizans yapılarındandır. Girişinde Bizans stili sütun başlıkları, 19 metre yüksekliğinde çift kademeli kasnağa oturan gösterişli konik bir kubbesi bulunur. 16. yüzyılda satın alınarak camiye çevrilmiş olup bu duruma dair Arap harfli iki Osmanlıca belgeden biri, batı cephesindeki giriş kapısı hizasında saçak altındaki kitabede yer almaktadır; kapıda hicri 968 (miladi 1560) tarihi yazılıdır ve yapı Fatih Camii adıyla anılmaya başlanmıştır. Batısındaki avlu duvarına Hasan İbn Ali adında biri tarafından bir çeşme yaptırılmıştır. 1855 depreminde minaresi, kubbesi ve güney duvarı hasar görmüş ve onarılmıştır. Temmuz 1920'de bölgenin Yunan ordusunca işgali sırasında yerli Rumlar tarafından bir süre yeniden kiliseye çevrilmiş, ancak Eylül 1921'de bölgeye gelen Kral Konstantinos'un karşı çıkmasıyla yeniden cami olarak kullanılmaya devam etmiştir. Kaynak: Mudanya Belediyesi" },
      "halil-aga-eski": { period: "1500 (Mudanya'nın en eski yapılış tarihli camisi)", founder: "Kethüda Halil Ağa", info: "Mudanya ilçe merkezinde, sahil şeridinin arkasındaki cadde üzerinde, girişe oldukça yakın bir konumda bulunur. Kare planlı yapının iç kısmında bir kubbe bulunmakla birlikte, kubbenin üzeri piramit tarzında kapatıldığından dışarıdan görünmez; bu özelliğiyle 'gizli kubbe' olarak adlandırılır. Taştan inşa edilmiş tek minareli caminin ağaçtan beyaz oyma bir minberi, klasik eski Osmanlı süslemeleriyle bezenmiş bir mihrabı ve ağaç şerit süslemeli bir tavanı vardır. Mermer sütunlu bir yan girişi de bulunan caminin kapısı üzerinde Osmanlıca yazılar yer alır; iç kısımda bayanlara ayrılmış bir balkon bölümü mevcuttur. Arka bahçesindeki hazirede Havace Hacı Ali bin Muhammet Hazretleri, Muhammet Necmettin Molla, Mudanya Müdürü Hurşit Ağa Mahdumu Ahmet Bey, Remzi Bey, Tevfik Efendi, Emine Seher Hanım, Mudanya Naibi İbrahim Efendi ile Elhac Salih Efendi'nin kerimesi Safiye Hatun'un kabirleri bulunmaktadır. Kaynak: Seyyah Çelebi" },
      "yildirim-camii-inegol": { period: "1398-1402 (I. Bayezid/Yıldırım Dönemi); günümüzdeki bina II. Abdülhamid Dönemi'nde yenilendi", founder: "I. Bayezid (Yıldırım Bayezid)", info: "İnegöl ilçe merkezinde, Cuma Mahallesi Nuri Doğrul Caddesi'nde, İshak Paşa Medresesi'nin yanında yer alır. İnegöl'ün en eski camisi olup Yıldırım Cami, Beyazıd Han Cami, Yıldırım Han Cami ve Cuma Cami adlarıyla da anılır. Özgün yapı I. Bayezid tarafından 1398-1402 yıllarında yaptırılmış, zamanla tahrip olması üzerine II. Abdülhamid döneminde yerine bugünkü gotik yapı inşa edilmiştir; yalnızca minarenin kaidesi özgünlüğünü korumaktadır. Evliya Çelebi Seyahatnâme'sinde kubbesinin kiremit örtülü olduğunu belirtir. 10,50 x 10,50 m ölçülerinde kare planlı yapının altıgen kaide üzerinde yükselen silindirik tuğla minaresi tek şerefeli olup şerefe üstünde çini süslemeler bulunur; minare kaidesi bir sıra taş, üç sıra tuğla ile almaşık örülmüş, gövde ve petek tuğladandır. İç ve dış duvarlar sıvalı olduğundan özgün malzeme ve teknik tam olarak belli değildir. Kasnak, pandantif ve kubbe yüzeyi bitkisel motifli kalem işleriyle, harim duvarları ise bitkisel bezemeler ve yazılarla süslüdür. Kaynak: Kültür Portalı" },
      "inegol-ishakpasa": { period: "873 (1468-69) yılından önce tamamlanmış; vakfiyesi Safer 891/Şubat 1486, ek vakfiyesi Cemaziyelevvel 892/Mayıs 1487 tarihli", founder: "İshak Paşa (Fatih Sultan Mehmed devri vezîriazamı)", info: "İnegöl'de şehir merkezini oluşturan külliyenin bir parçasıdır; vakfiyede cami, medrese, türbe, imaret, han ve ahırlardan oluşan külliye tanımlanmakta olup imaret, han ve ahırlar günümüze ulaşmamıştır. İnşa kitabesi bulunmayan cami, zâviyeli/tabhâneli plan grubundandır ve yan mekânları eyvanlı olarak düzenlenmiştir. Taş-tuğla almaşık örgülü duvarlarında altta dikdörtgen, üstte sivri kemerli iki sıra pencere bulunur. Mihrap ekseninde yer alan iki birimden kuzeydeki daha geniş olup üçgen geçişli, mukarnaslı aydınlık fenerli bir kubbeyle; mihrap yönündeki, biraz daha küçük tutulan birim ise prizmatik üçgen geçişli bir kubbeyle örtülüdür. Kuzeye doğru uzanan dikdörtgen tabhâne mekânları güneyde kubbe, kuzeyde aynalı tonozla örtülüdür. Dikdörtgen nişli, köşeleri sütuncelerle yumuşatılmış mihrabın yedi sıralı zarif bir mukarnas yaşmağı vardır; niş çevresindeki çerçevenin sonradan yenilendiği anlaşılmaktadır. Kuzeydeki beş birimli son cemaat yeri altı kalın payeye oturan sivri kemerli açıklıklara sahip olup üstü kubbelerle örtülü, revak cephesi kirpi saçak altında geometrik tuğla düzenlemeleriyle bezelidir; kapı üzerindeki dört satırlık Arapça kitabe 1294 (1877) tarihli bir tamire işaret eder. Son cemaat yerinin batı köşesinden yapıya dışarıdan bitişik minareye geçilir; beş cepheli, taş-tuğla almaşık örgülü kaide ile pabuç kısmı özgün olup gövde, şerefe, petek ve külah sonradan yenilenmiştir. Mihrap ekseninde bulunan şadırvan tamamen yeniden yapılmış olup altıgen planlı hazne ve kiremit kaplı ahşap sundurmaya sahiptir. Kaynak: İslam Ansiklopedisi" },
      "bali-bey-camii-yenisehir": { period: "İnşa kitabesi bulunmadığından kesin tarihi bilinmiyor (Fatih Sultan Mehmed Dönemi eserleri arasında değerlendirilir)", founder: "Balı Bey (İzmir fatihi Baş vezir Beyazıd Paşa'nın kardeşi şehit Hamza Bey'in oğlu)", info: "Fatih devri eserleri arasında değerlendirilen caminin inşa kitabesi bulunmadığından yapım tarihi kesin olarak bilinmemektedir. Güneyindeki hazirede iki mezar taşı yer alır: birincisinde Balı Bey'in adı belirtilmeyen bir oğlunun 910 H./1504-05 M. tarihinde vefat ettiği, ikincisinde ise yalnızca 956 H./1549-50 M. tarihi yazılıdır. Yenişehir'deki Şemaki evinin bahçesinde muhafaza edilen 1159 H./1746-47 M. tarihli üç satırlık mermer bir kitabe, bazı yayınlarda caminin tamir kitabesi olarak değerlendirilir; bu kitabede 'Halil Beğ bin merhum mirliva Kadr-i Alişan Mehmed Beğ'in' camiyi Beyt-i Mamur'a döndürdüğü belirtilmektedir. Cami; kare planlı kubbeli bir ibadet mekânı, doğu ve batısında eş boyutlu kare planlı ve kubbeli küçük yan kanatlar ile kuzeyinde doğu-batı doğrultusunda dikdörtgen planlı, düz tavanlı bir son cemaat yerinden oluşur. Kaynak: bursa.com" },
      "kumluk-camii-yenisehir": { period: "14. yüzyıl (zaman içinde birçok kez onarım görmüştür)", founder: "Osman Gazi", info: "Yenişehir Murat Paşa Mahallesi'nde bulunan Kumluk Camii, 14. yüzyılda Osman Gazi tarafından yaptırılmıştır. Osman Gazi'nin burayı merkez edinerek Yenişehir adını verdiği, şehri kurarken evler, mabetler ve çeşitli yapılar inşa ettirdiği anlatılır; kuruluş dönemi kaynakları bir saraydan söz etmese de Neşrî'nin 'taht kurdu' ifadesi, Bursa başkent oluncaya kadar burasının kullanıldığını göstermektedir. Caminin en önemli özelliği, Osmanlı Devleti'nin ilk hutbesinin burada okunmuş olmasıdır; bu yönüyle Osmanlı tarihinde ayrı bir yere sahiptir. Zaman içinde birçok onarımdan geçen yapı, günümüze kadar ulaşmıştır. Kaynak: Bursa'da Zaman" },
      "voyvoda-cinarli-camii-yenisehir": { period: "1415 (kesin yapım tarihi bilinmemekle birlikte, bazı kaynaklarda 15. veya 17. yüzyıla da tarihlenir); kubbesi 1830'da onarılmıştır", founder: "Sungur Paşa (Amasyalı Sadettin Bey'in oğlu)", info: "Yenişehir'in en eski camilerinden biri kabul edilen yapı, Bali Bey Camii ve Külliyesi'nin yakınında, onun kuzeyinde yer alır. Kesin yapım tarihi bilinmemekle birlikte 15. veya 17. yüzyıla ait olabileceği ileri sürülmektedir. Fener kubbeli camiler türünden olan yapı, bahçesindeki asırlık çınar ağacından dolayı halk arasında 'Çınarlı Camii' olarak da anılır. Mehmet Göktekin'in anılarına göre caminin banisi, 1295 yılında Osman Gazi'ye Yenişehir ovasında katılan Amasyalı Sadettin Bey'in oğlu Sungur Paşa'dır. 1305 doğumlu olan Sungur Paşa, Şehzade Süleyman Paşa ile birlikte Gelibolu'da pek çok yararlılık göstermiş, uzun süre I. Murad'ın sancaktarlığını yapmıştır. Sungur Paşa, 1415 yılında bu cami ile bitişiğindeki medreseyi yaptırmıştır; medrese 1922 yılında yıkılmıştır. 19. yüzyıl başlarında çökme tehlikesi gösteren kubbe, 1830 yılında dönemin Yenişehir Voyvodası (yöneticisi/valisi) Ali Bey tarafından aslına uygun şekilde onarılmıştır. Kaynak: bursa.com" },
      "sinan-pasa-camii-kulliyesi-yenisehir": { period: "Kesin olarak bilinmemekle birlikte, elde edilen belgelere göre yaklaşık 1572-1573", founder: "Sinan Paşa", info: "Halk arasında 'Kurşunlu Han' olarak da anılan Sinan Paşa Külliyesi; cami, medrese, imaret-aşhane, arasta ve girişlerden oluşmaktadır. Günümüzde Sinan Paşa Yurdu olarak hizmet veren külliyenin bütününden yalnızca az bir bölüm ayakta kalabilmiş olup, halen kullanılabilir durumdaki kısımların başında medrese, imaret ve cami gelmektedir. Külliyenin banisi Sinan Paşa, 1520 yılında Arnavutluk'ta Topoyani'de doğmuş, küçük yaştan itibaren yetiştirilen devşirmelerden olup Kanuni Sultan Süleyman'ın aşçılığını yapmıştır. Sancak beyliği görevinde bulunmuş; ikiye ayrılan Yemen'i birleştirip yeniden Osmanlı yönetimine kazandırmasındaki başarısından dolayı kendisine 'Yemen Fatihi', ayrıca 'Tunus Fatihi' unvanları verilmiştir. Dördüncü vezirliğe kadar yükselmiş, İran seferinde komutanlık yapmış ve ardından sadrazam olmuştur; III. Murad ve III. Mehmed dönemlerinde toplam dört kez sadrazamlık görevine getirilmiş, 3 Nisan 1596'da vefat etmiştir. Külliyenin kesin yapım tarihi hiçbir belgede yer almamakla birlikte, Topkapı'daki Sinan Paşa arşivinde bulunan bir belgede Yenişehir'den ve bu külliyeden söz edilmektedir; buna göre külliyenin kurulduğu arazi Sultan Orhan tarafından Yenişehir halkına mera olarak sınırları belirlenmiş bir mülk şeklinde verilmiş, daha sonra kasaba halkı bu arazi üzerine cami, medrese, imaret ve kervansaraydan oluşan külliyenin yapılabilmesi için toprakların Sinan Paşa'ya devredilmesine karar vermiştir. Bu belgeler ışığında külliyenin yapımının yaklaşık 1572-1573 yıllarına rastladığı değerlendirilmektedir. Kaynak: Yenişehir Belediyesi" },
      "yenisehir-ulu": { period: "1324-1362 (Orhan Gazi Dönemi); en son 1923 yılında tadilat görmüştür", founder: "Orhan Gazi", info: "Yenişehir ilçesi Ulucami Mahallesi Ulucami Sokak'ta bulunan cami, kayıtlara göre Orhan Gazi (1324-1362) tarafından yaptırılmıştır. Büyük bir minareye sahip olduğu için halk arasında 'Ulu Cami' adıyla anılır. Birçok defa tadilat görmesine rağmen özgün yapısı korunmuş, en son 1923 yılında onarım geçirmiştir. Taş kullanılarak ve kubbesiz olarak inşa edilen caminin minaresi, çokgen tuğla kaideli ve tek şerefelidir; günümüze bozulmadan ulaşan minarenin on iki kenarlı kaidesi taş ve tuğla işçiliğiyle örülmüştür. Kaideden silindirik tuğla gövdeye geçiş üçgenlerle sağlanmış, gövdeye geçişte ve şerefe altında birer bilezik yer almaktadır. Minarenin dikkat çeken özellikleri, gövdesindeki oran uyumu ile şerefe altındaki yedi sıra stalaktitin düzenli dizilimidir. Yarhisar'daki Orhan Gazi Camii'nin minaresiyle benzerlikler taşımakla birlikte, Yenişehir Ulu Camii minaresinin şerefesi daha zengin görünümlü olup gölge-ışık etkilerini daha belirgin kılan bir yapıya sahiptir. Kaynak: Bursa Ulu Cami" },
      "yarhisar-orhan-gazi-camii": { period: "14. yüzyıl (Orhan Gazi Dönemi, salt. 1324-1362); yapı büyük ölçüde yenilenmiştir", founder: "Orhan Gazi (Sultan Orhan Bey)", info: "Yenişehir'e bağlı Yarhisar Köyü'nde bulunan bu camiden pek çok Osmanlı kroniğinde söz edilir. Orhan Bey, baba yurdu saydığı bu köye bir cami, yanı başına bir çeşme ve bir de hamam yaptırmıştır; bu üç eserden cami ile çeşme günümüzde de kullanılmakta, hamamdan ise yalnızca yıkıntı kalmıştır. Orhan Gazi tarafından yaptırılan cami, aynı zamanda 'Nilüfer Hatun Camii' olarak da anılmaktadır. Dikdörtgen planlı caminin üzeri düz tavanla örtülü olup, iki sıra tuğla ve iki sıra taşla örülen duvarların içinde bazı taş süslemelere rastlanır; yapı büyük ölçüde yenilenmiştir. Köyde ayrıca, Orhan Bey tarafından yaptırıldığı tahmin edilen ve çeşitli bezemelere sahip tarihi bir hamam da bulunmaktadır; bugün oldukça bakımsız durumda olan bu yapının koruma altına alınması gerekmektedir. (Ayverdi I. (1966), s. 201; Vakıflar (1986) IV. s. 627) Kaynak: bursa.com" },
      "hasan-bey-camii-mudanya": { period: "Hicri 1063 / Miladi 1652-1653 (kapıdaki Türkçe kitabede kuruluş 1644, onarım 1975 olarak da geçmektedir)", founder: "Mirliva Hasan Bey (Mısır Mirlivası Hasan Bey)", info: "Mudanya'da Hasanbey Mahallesi'nde bulunan, minaresiyle kolayca fark edilen bir camidir. Kitabesine göre Mirliva Hasan Bey tarafından yaptırılmıştır. Kuzey-güney doğrultusunda dikdörtgen planlı yapının duvarları moloz taş ve ahşap hatıllı olup ahşap çatısı kiremitle örtülüdür; kuzeybatısında tek şerefeli bir minare, minarenin kuzeyinde ise kitabeli bir çeşme yer alır. Giriş kapısındaki taş kitabede inşa tarihi Hicri 1063 (Miladi 1652-1653) olarak belirtilirken, kapı üzerindeki başka bir Türkçe yazıda kuruluş 1644, onarım tarihi ise 1975 olarak geçmektedir. Hasan Bey Türbesi'ndeki iki kitabeli lahitten birinde 'Mısır Mirlivası Hasan Bey' ibaresi bulunur; çeşmedeki iki satırlık taş kitabe de yine caminin Hasan Bey tarafından yaptırıldığını doğrulamaktadır. Kaynak: Bursa Büyükşehir Belediyesi" },
      "omer-bey-camii-mudanya": { period: "1715", founder: "Ömer Bey", info: "Mudanya ilçesi Ömerbey Mahallesi Halitpaşa Caddesi No:72B'de, cadde üzerinde bulunur; adını yaptıran Ömer Bey'den alır. 200 m² büyüklüğündeki kare planlı cami birçok kez onarım görmüş olmakla birlikte, yapıldığı tarihten kalma minaresi özgünlüğünü korumaktadır. İçinde ahşap bir minber ve klasik süslemeli bir mihrap ile kadınların namaz kılması için bir balkon bölümü bulunur. 2018 yılında aslına sadık kalınarak restore edilmiştir. Kaynak: bursa.com.tr" },
      "tekke-i-cedidi-camii": { period: "1677 (17. yüzyıl); 1975'te betonarme olarak yeniden inşa edildi", founder: "Hacı Mehmet Ağa (tahmini)", info: "Cami avlusunun güney duvarındaki kitabeye göre 1677 yılında inşa edilmiştir. 1975'te özgün yapı yıkılarak yerine bugünkü betonarme cami yapılmıştır. Kare planlı yapının sekizgen kasnağa oturan büyük bir kubbesi vardır; kaidesine kadar yıkılmış olan minaresi de yeniden inşa edilmiştir. Caminin, haziresinde medfun bulunan Hacı Mehmet Ağa adlı bir zat tarafından yaptırıldığı tahmin edilmektedir. 17. yüzyıl eseri olan cami, geçirdiği onarımlarla özgün niteliğini büyük ölçüde yitirmiş olup günümüzde basık kubbeli ve tek şerefeli bir görünümdedir. Kaynak: bursa.com.tr" },
      "tekke-i-atik": { period: "1453 (kapı üzerindeki levhaya göre)", founder: "Kesin olarak bilinmemekle birlikte Hacı Ali Zağili Mağrabi tarafından yaptırıldığı düşünülmektedir", info: "Giriş kapısının üzerinde 1453 tarihi yazılı bir levha bulunmaktadır. Kuzey-güney doğrultusunda dikdörtgen planlı cami, asıl ibadet mekânı ve son cemaat yerinden oluşur; üzeri ahşap kırma çatı ve kiremit ile örtülüdür. Mihrap, mavi-beyaz kare biçimli çini panolarla kaplanmıştır. Kaynak: bursa.com.tr" },

      "cumalikizik-camii": { period: "Erken Osmanlı (Cumalıkızık vakıf köyü)", founder: "Orhan Gazi vakıfları", info: "UNESCO Dünya Mirası Listesi'ndeki Cumalıkızık köyünün tarihi camisidir. Osmanlı'nın kuruluş dönemi vakıf köyü dokusunun canlı örneğidir." },
      "umurbey-carsi-camii": { period: "1897 – 1899 (yapım), 1910 – 1912 (kapsamlı onarım)", founder: "Umurbey halkı (banisi hakkında ayrıntılı kayıt yok)", info: "Bursa'nın Gemlik ilçesine bağlı, III. Cumhurbaşkanı Celal Bayar'ın memleketi olan Umurbey Beldesi'nin çarşı merkezinde yer alır. 1910 yılındaki tamire ait kitabe cami girişinde bulunmaktadır. Kareye yakın planlı yapı, dört sütunun taşıdığı merkezi bir kubbe ve çevresindeki 10 pencere ile dikkat çeker; şadırvan ve cami içi kalem işçilikleri özenlidir. Minaresi bir dönem yıkılmış olup 2013 itibarıyla minaresiz hizmet vermekteydi. Bursa Büyükşehir Belediyesi'nin 29.03.2016'da tamamladığı restorasyon çalışmasıyla minare yenilenmiş, Gemlik Belediyesi'nin meydan projesiyle bütünleşik bir çevre düzenlemesi de gerçekleştirilmiştir." },
      "koza-hani-mescidi": { period: "15. yüzyıl sonu (II. Bayezid Dönemi)", founder: "II. Bayezid", info: "Osmangazi ilçesi Şehreküstü Mahallesi'nde, Uzun Çarşı Caddesi üzerindeki Koza Hanı'nın avlusunda, şadırvanın üzerinde yer alır. Bursa'daki han mescitlerinin en güzel örneklerinden biri kabul edilir ve tümüyle kesme taştan inşa edilmiştir. Mescide yüksek bir merdivenle çıkılmaktadır; bu merdiven eskiden demirken, yapılan onarımda özgün biçimine uygun olarak kagir hale getirilmiştir. Günümüzde sağlam durumda olup ibadete açıktır." },
      "meydancik-camii": { period: "Fatih Sultan Mehmed Dönemi, 1497'den önce", founder: "Kazzazoğlu Sole Mehmet Paşa", info: "Yıldırım ilçesi Meydancık Mahallesi Alancık Sokak'ta bulunur; mülkiyeti Vakıflar Genel Müdürlüğü'ne aittir. Sole Mehmet Paşa'nın Bursa'da yaptırdığı üç mescitten biridir. 7,00 x 7,00 metre iç ölçülerinde kare planlı asıl ibadet alanı ile 3,65 metre derinliğinde bir son cemaat yerinden oluşur; girişi sivri kemerlidir ve duvarları üç sıra tuğla, bir sıra kesme taş ile örülmüştür. Asıl ibadet alanının üzeri büyük bir kubbe, son cemaat yerinin üzeri ise tonozla örtülüdür. Birçok kez onarım gören yapının batısındaki tuğla gövdeli, tek şerefeli minaresi 1913 onarımında yenilenmiş olup girişte buna ait tamirat kitabesi bulunur. Kubbe kasnağında üç alt sırada dört sivri kemerli pencere yer alır; güneydeki iki pencere sonradan kapatılarak dolaba dönüştürülmüştür. Dış köşeliklerinde silindirik gövdeli sütunceleri bulunan mihrap sade ve dikdörtgen çerçevelidir. Kaynak: Yıldırım Belediyesi" },
      "haci-ivaz-pasa-camii": { period: "II. Murad Dönemi (15. yüzyıl); 1970'te yeniden inşa", founder: "Hacı İvaz Paşa", info: "Yeşil Külliyesi'nin mimarı Hacı İvaz Paşa tarafından II. Murad devrinde yaptırılmıştır; Pirinç Hanı karşısında, Tavuk Pazarı semtinde, medrese ile aynı avluyu paylaşan İvaz Paşa Külliyesi'nin bir parçasıdır. Bir vakfiyede İmadiye Mescidi olarak anılmış, zamanla İvaz Paşa Mescidi, Kazzaziye/Kazazhane Mescidi ya da Tavuk Pazarı Mescidi gibi adlarla da bilinmiştir. 1642 yılına kadar mescit olarak hizmet vermiş, Seyyid Mehmed Efendi'nin vakfettiği bir minberle camiye dönüştürülmüştür. 1958'deki çarşı yangınında tamamen harap olmuş, 1970 yılında Bursa Eski Eserleri Sevenler Kurumu'nun girişimiyle yeniden inşa edilmiştir. Kuzey-güney doğrultusunda dikdörtgen planlı olup üzeri iki kubbeyle örtülüdür; beden duvarları kesme taş ve tuğla örgülüdür, tek minarelidir. Kaynak: bursa.com" },
      "hatice-isfendiyar-sultan-camii": { period: "1500 (Fatih Sultan Mehmed Dönemi)", founder: "Hatice Sultan (İsfendiyaroğlu İbrahim Bey'in kızı)", info: "Gökdere'de Kamberler Mahallesi'nde bulunan bu cami, uzun süre adı bilinmeden ayakta kalmış, belediyenin Kamberler'deki evleri istimlak ederek meydan düzenlemesi yapmasıyla gün yüzüne çıkmıştır. Kitabesine göre 1500 yılında, II. (Çelebi) Mehmed'in torunu Hatice Sultan tarafından yaptırılmıştır. Hatice Sultan'ın babası İsfendiyaroğlu İbrahim Bey, annesi Çelebi Mehmed'in kızı Selçuk Hatun'dur; eşi ise Fatih Sultan Mehmed dönemi sadrazamı Mahmud Paşa'dır. Kubbeyle örtülü, kare planlı caminin girişinde bir son cemaat yeri bulunur; duvarları tuğla ve taşla örülüdür. Osmangazi Belediyesi'nin yürüttüğü 'Kamberler Tarih ve Kültür Parkı Projesi' (2008) kapsamında çevresindeki eski yapılardan ayıklanarak bugünkü görünümüne kavuşmuştur. Hatice Sultan Camii veya Hatice İsfendiyar Camii olarak da anılır; namaz vakitleri dışında kapalıdır. Kaynak: Seyyah Çelebi" },
      "gazi-timurtas-pasa-camii": { period: "1390 (bazı kaynaklara göre Yıldırım Bayezid Dönemi)", founder: "Ali Bey (Timurtaş Paşa'nın oğlu) — bazı kaynaklara göre Kara Timurtaş Paşa", info: "Osmangazi'nin Demirtaş Mahallesi'ndeki cami, Timurtaş Paşa'nın oğlu Ali Bey tarafından 1390 yılında yaptırılmıştır; bazı kaynaklarda ise Yıldırım Bayezid'in emiri Kara Timurtaş Paşa'ya atfedilir ve Demirtaş Paşa Camii olarak da anılır. 'Ters T planlı', 'zaviyeli', 'yan mekânlı' olarak da adlandırılan, tuğla ve kesme taştan yapılmış 'Bursa tipi cami' grubundandır; ortasında aydınlık fenerli merkezi bir kubbe, yanlarında tonoz örtülü eyvanlar bulunur. Caminin en dikkat çekici özelliği, saat kulesini andıran ilginç minaresidir: cami binasından ayrı olarak sokağın karşısında, birbirine kemerlerle bağlı altı tuğla ayak üzerine oturtulmuş, Osmanlı mimarisinde benzeri bulunmayan bu minarenin kaidesinin ortasında bir şadırvan yer alır. Minare, Bursa Eski Eserleri Sevenler Derneği tarafından 1966 yılında onarılmıştır. Kaynak: Mustafa Canbaz" },
      "azeb-bey-camii": { period: "1456 (II. Murad Dönemi)", founder: "Azeb Bey b. Abdullah", info: "Muradiye semtinde Kullukçu Sokağı'nda bulunur. Kapısı üzerindeki Arapça kitabesine göre, II. Murad'ın komutanlarından Ümera'dan Azeb Bey b. Abdullah tarafından 1456 yılında yaptırılmıştır. Bursa'da bir hayli örneği bulunan, son cemaat yeri payeli, kare planlı ve tek kubbeli cami tipindendir; duvarları iki sıra tuğla ve moloz taşla örülmüştür. Son cemaat yeri iki kemerle ayrılmış, üstleri beşik tonozlu üç bölümden oluşur; kare mekândan 5,80 metre çapındaki kubbeye geçiş Türk üçgenleriyle sağlanmıştır. Batıdaki minarenin kaidesi tuğla ve taştan, silindirik gövdesi tuğladandır; şerefe altında dört sıra kirpi saçak dizisi bulunur ve sivri külahı kurşun kaplıdır. Sağ tarafındaki Azeb Bey Türbesi de kare planlı ve kubbeyle örtülüdür; mekân 19 pencereyle aydınlatılmıştır. Yapı en son 1947 yılında tamir edilmiş olup sağlam ve ibadete açıktır. Kaynak: Kültür Portalı" },
      "ahmed-dai-camii": { period: "1471 (II. Mehmed Dönemi)", founder: "Edincikli Hızıroğlu Yahşi Bey", info: "Cumhuriyet Caddesi ile Ahmed Dai Sokağı'nın kesiştiği yerdedir; bir mahalle camii tipindedir. Camiye adını veren Ahmed Dai'nin yapıyla doğrudan bir ilişkisi yoktur, sadece Ahmed Dai Mahallesi'nde bulunduğu için bu adı almıştır — Ahmed Dai, Gazi Süleyman Paşa'nın hizmetinde bulunmuş ve I. Murad döneminde vefat etmiş ünlü bir şairdir. Revakı üstündeki yüksek kalkanda üç çökertme tuğla şekilleriyle süslenmiş, kalkan duvarlarının üç tarafında Bursa'ya özgü kabartma bir kuşak dolaşmaktadır. 7,57 x 7,57 metre iç ölçülerinde, kare planlı ve tek kubbeli olan cami, girişinde 4,47 metre boyutlarında bir son cemaat yerine sahiptir; içi on pencereyle aydınlanır. Tespihlik ve mihrabı Yeşil Türbe çinileriyle kaplıdır. Minaresi 24 dilimli, tuğla işlemeli bir yapıdır. Cami 1953 yılında Bursa Eski Eserleri Sevenler Kurumu tarafından onarılmış olup halen sağlam ve ibadete açıktır. Kaynak: bursa.com" },
      "mustafakemalpasa-yesil-camii": { period: "Bilinmiyor (yakın zamanda tamirat geçirdiği düşünülüyor)", founder: "Bilinmiyor", info: "Mustafakemalpaşa ilçesi Çırpan Mahallesi, Yeşil Cami Sokak No:1'de yer alır; ilçenin ilgi çeken camilerinden biridir. Harim üzeri, dört yan kubbenin ortasında onlardan biraz daha büyük bir ana kubbe ile örtülüdür. Dört küçük kubbeyle örtülü son cemaat yerine, oldukça geniş bahçe avlusundaki bir kapıdan girilir; bu kapı küçük bir camiyi andıran görünümü ve caminin iki minaresiyle birlikte hoş bir manzara oluşturur. Dikdörtgen planlı yapı, harime son cemaat yerindeki kapıdan girilecek şekilde düzenlenmiştir. Mihrap seramikle kaplanmış, mihrap nişinin üstü ve yan duvarlar ayetlerle süslenmiştir. Minber ve kürsü ahşap malzemeden, sade bir görünümle yapılmıştır. Kaynak: Erol Şaşmaz" },
      "mustafakemalpasa-yenickoy-camii": { period: "1901 (kitabesine göre)", founder: "Hızır Paşa", info: "Mustafakemalpaşa'nın Devecikonağı bucağına bağlı Yenice Köyü'ndedir. 51x62 cm ölçülerindeki mermer kitabesine göre Hızır Paşa tarafından 1901 yılında yaptırılmıştır. Kuzey-güney doğrultusunda dikdörtgen planlı olan camiye sonradan bir son cemaat yeri eklenmiştir; ahşap çatıyla örtülüdür. Güney duvarının ortasında yarım yuvarlak mihrap, kuzeyinde ise giriş kapısı bulunur. Güney duvarında altlı üstlü ikişer, doğu ve batı duvarlarında ikişer alt üçer üst, kuzey duvarında iki alt pencereyle aydınlatılır; alttaki pencereler yuvarlak kemerli, üsttekiler dikdörtgendir. Giriş kısmında antik malzemelerle yapılmış bir çeşmesi vardır. Bizans dönemi kalıntıları bulunan köyün adına 17. yüzyıl kadı sicillerinde rastlanmaktadır; Lala Şahin Paşa'nın vakıf köyü olup, Bagenoğulları ailesi tarafından kurulduğu rivayet edilmektedir." },
      "mustafakemalpasa-muftu-camii": { period: "1894-1895", founder: "Şeyh Müftü adına, Naib Şefik Bey'in katkılarıyla", info: "Şeyhmüftü Mahallesi Balıkesir Caddesi üzerinde, Mustafakemalpaşa'dadır. Harimin kuzeyindeki giriş kapısı üzerinde yer alan üç satırlık mermer kitabede, 'Şeyh Müfti Cami Şerifi'nin 1894-1895 yılında Naib Şefik Bey'in yardımlarıyla yapıldığı yazılıdır. Kuzey-güney doğrultusunda dikdörtgen planlı olup güneyde harim, kuzeyde sonradan eklenen son cemaat yeri, batı cephenin kuzey köşesinde minare bulunur. Harimde ortada dört sütun üzerinde yükselen bir kubbe, yanlarda ise düz tavan yer alır. Beden duvarlarından alçak olan son cemaat yeri düz çatıyla örtülüdür; ahşap desteklere oturan beş yuvarlak kemer açıklığı camekanlı olup orta bölüm kapı olarak düzenlenmiştir. Doğu cephede güneyde harim, kuzeyde son cemaat yeri yer alır; harim cephesindeki alt pencereler sivri kemerli ve demir parmaklıklı, üst pencereler yuvarlak kemerlidir. Batı cephenin güneyinde harim, kuzeyinde türbe ve minare bulunur. Cepheler moloz taş ve tuğlayla düzensiz bir teknikte örülmüş, köşelerde kesme taş kullanılmıştır; son cemaat yeri ve kubbe kasnağı ahşaptır. Kaynak: Kültür Portalı" },
      "mustafakemalpasa-melikkoyu-camii": { period: "Bilinmiyor (eski caminin üzerine yeniden inşa edilmiş)", founder: "Bilinmiyor", info: "Mustafakemalpaşa ilçesine bağlı, Bursa il merkezine yaklaşık 98 km mesafedeki Melik Köyü'ndedir. Mevcut cami, eski caminin üzerine daha büyük ölçekte yeniden yapılmıştır; eski minare orijinal haliyle korunmuş, yeni yapılan minareyle birlikte iki minareli bir cami ortaya çıkmıştır. Kareye yakın planlı olan yapının kurşun kaplı bir kubbesi vardır. Batı yönündeki eski minarenin üzerinde yapım kitabesi bulunur ve şerefe etrafındaki işlemeleriyle dikkat çeker. Yeni minare daha yüksek olup iki şerefelidir. Üç kubbeden oluşan son cemaat yerine avludan iki kapıyla giriş yapılmaktadır. Kaynak: Erol Şaşmaz" },
      "mustafakemalpasa-lala-sahin-pasa-kulliyesi": { period: "1348 öncesi (vakfiye tarihi: Haziran 1348)", founder: "Rumeli Beylerbeyi Lala Şahin Paşa", info: "Mustafakemalpaşa'nın eski adı Kirmasti olan merkezinde, Kirmasti çayı kıyısındaki bir parkın içinde yer alır; cami, medrese ve türbeden oluşan bir külliyedir. Lala Şahin Paşa'nın 1348 tarihli vakfiyesine göre caminin karşısında bir zaviye de bulunuyordu; paşa ayrıca Kirmasti'de hamam, dükkânlar ve çay üzerinde ahşap bir köprü yaptırmıştı. Bu eserler, 1339-40 civarında Bizanslılara karşı kazanılan Yalakabad (Yalova) Muharebesi'nin ganimetleriyle inşa ettirilmiştir. Külliyeden günümüze yalnızca türbe sağlam ulaşmış; cami tamamen yok olmuş, minarenin şerefeyle birlikte yıkılan gövdesinden yalnızca alt kısmı ve medrese duvarlarının bazı parçaları kalmıştır. Minarenin kare kaidesi kesme taş ve tuğladan, gövdesi yalnızca tuğladandır; kaidedeki mermer kitabeye göre minare 1823'te yenilenmiştir. Medreseden yalnızca bazı duvar parçaları günümüze ulaşmış, üzerine Cumhuriyet'in ilk yıllarında bir okul inşa edilmiştir. Kitabesi olmayan ancak vakfiyesinden 1348'den önce yapıldığı anlaşılan türbe, 1787'de onarılmış, 1948'de Maarif Vekâleti tarafından restore edilmiş olup halen belediye tarafından depo olarak kullanılmaktadır. Kare planlı gövdesi sivri külahlı bir kubbeyle örtülü olan türbe, muhtemelen eski bir Bizans yapısının duvar ve mimari parçalarından yararlanılarak inşa edilmiştir; özellikle güneydoğu cephesinde Bizans işçiliğine ait kademeli kemerler, tuğla rozet ve kirpi saçak süslemeleri dikkat çeker, sekiz dilimli kubbesi ise Selçuklu üslubunu yansıtır. Zaviyenin hiçbir izi kalmamış, muhtemelen 1861-62'den sonra ortadan kalkmıştır; hamam ve ahşap köprünün de günümüze ulaşan izi yoktur. Kaynak: İslam Ansiklopedisi" },
      "mustafakemalpasa-kestelek-koyu-camii": { period: "Eski cami: Eylül 1886 (Muharrem 1304 H.); köyün yerleşim geçmişi çok daha eskiye uzanır", founder: "Eski (Hacı Hasan) caminin banisi net değil; vakıf kayıtlarında adı geçmektedir", info: "Kestelek, Mustafakemalpaşa ilçesinin Çaltılıbük bucağına bağlı, ilçe merkezine yaklaşık 23 km uzaklıkta, Mustafakemalpaşa çayının hemen batısında bir köydür. Bilge Umar'a göre köyün adı 'kestel' (hisar) kökünden 'hisarcık' anlamında türetilmiştir; yakınındaki kale kalıntısı bu görüşü destekler. 1830'larda bölgeyi gezen seyyah Charles Texier, Kirmasti'den 24 km sonra ulaşılan 40-50 haneli küçük bir köy olarak Kestelek'ten ve hemen ardından görülen tuğla-taş duvarlı bir Bizans şatosundan söz eder; bu kalenin Uluabat (Lopadion) Kalesi ile yaşıt olduğunu belirtir. Tepe üzerinde, çevredeki yolları gözetleyebilecek konumdaki kalenin önemli bir bölümü halen ayaktadır; köylülere göre Osmanlı devrindeki Sincan kazasının merkezi bu kaledir. Köyün yanındaki maden ocağında da antik yerleşim kalıntıları çıkmıştır; buranın Bizans dönemi Kastallos kalesi olduğu düşünülmektedir. Köydeki modern caminin yerinde, vakıf kayıtlarına Hacı Hasan Camisi adıyla geçen eski bir cami bulunuyordu; avlusundaki 33x66 cm ölçülerindeki üç satırlık yazıtta bu caminin Eylül 1886'da (Muharrem 1304 H.) yaptırıldığı belirtilir. Kirmasti'nin ilçe merkezi olmasına kadar Sincan Bucağı'nın merkezi olan köy, 1907 tarihli Hüdavendigâr Vilayeti Salnamesi'nde 98 hane olarak kayıtlıdır. Köyde koruma altına alınmış çok eski bir servi ağacı, eski bir mezarlık ve mezar taşları bulunur; yakınındaki Etibank'a ait 'Eskiköy yeri' denilen madende bor çıkarılmakta olup buradan da çok sayıda eski yerleşim kalıntısı çıkmaktadır. Kaynak: Bursa Gazeteciler Cemiyeti / bursa.com" },
      "mustafakemalpasa-hamzabey-camii": { period: "Vakıf 1462-63; günümüzdeki cami 1950'de tamamen yenilenmiş", founder: "Hamza Bey (Murat Bey'in oğlu) — vakfeden olarak anılır", info: "1950 yılında tamamen yenilenen caminin kendi tarihini gösteren bir kitabesi yoktur. Caminin güneyindeki türbenin kuzey cephesinde, giriş kapısının iki yanında yer alan ve metin bütünlüğü taşıyan kitabelerde, Murat Bey'in oğlu Hamza Bey'in 1462-63 yılında üç değirmeni ile Kara Keçülü'deki ve Bolu'daki mülklerini tekkesine vakfettiği yazılıdır. Kare planlı türbe pandantifli bir kubbeyle örtülü olup içten sıvalıdır; beden duvarlarının dış yüzü altta kesme taş, üstte tuğla ve harç karışımıyla örülmüştür. Doğu cephesinde antik bir mezar taşı devşirme malzeme olarak kullanılmıştır. Kaynak: Mustafakemalpaşa Belediyesi" },
      "mustafakemalpasa-seydiali-koyu-camii": { period: "1885", founder: "Köy halkı (Bulgaristan göçmenleri)", info: "Seydi Ali köyü, Bursa il merkezine 95 km, Mustafakemalpaşa ilçesine ise 10 km uzaklıktadır. Köy, 1877-78 Osmanlı-Rus Savaşı sonrasında Bulgaristan'dan gelen göçmenler tarafından kurulmuştur; adını, köy girişindeki mezarlıkta bulunan türbede yatan ve köyün kuruluşunda emeği geçen ilk yerleşimci Seydi Ali'den almaktadır. Köy camisi 1885 yılında yapılmıştır; farklı dönemlerdeki bakım ve tadilatlarla özgün halinden bir ölçüde uzaklaşmıştır. Kareye yakın planlı olan cami, kiremit kaplı kırma çatıya sahiptir. Tek şerefeli minaresi güzel bir görünüm sergiler; mihrabı seramik malzemeyle, minber ve kürsüsü ahşaptan yapılmıştır. Cami içindeki ahşap tavan rozet ve madalyonlarla süslenmiştir. Kadınlar mahfiline harim içindeki ahşap bir merdivenle çıkılmaktadır." },
      "mustafakemalpasa-ayaz-koyu-camii": { period: "Türbe 1442-43; cami 1899-1900 (kitabeye göre)", founder: "Ayas Paşa (türbe, cami ve mescit); türbe için Ayas Bin Sinan Bin Ayas", info: "Ayaz köyü, Mustafakemalpaşa ilçesine bağlı olup Bursa il merkezine 95 km, ilçe merkezine 10 km uzaklıktadır. Köy, İstanbul'un fethinden 35 yıl önce, 1416 yılında, Lala Şahin Paşa'nın komutanlarından ve rivayete göre Fatih Sultan Mehmed'in hocalarından olan Ayas Paşa tarafından kurulmuştur; köyü de içine alan geniş bir tımar arazisi, savaşlardaki başarılarından ötürü kendisine verilmiştir. 1530 tarihli belgelere göre köyde 4 hane yaşamaktaydı. Ayas Paşa 1442 yılında bir türbe, cami ve mescit yaptırmış; caminin güneyindeki türbe onun eseri olup kendi mezarının da burada olduğu söylenir. Türbenin 1443 yılında Ayas Bin Sinan Bin Ayas tarafından yaptırıldığı, hem türbe girişindeki kitabeden hem de 1936'da Uludağ Mecmuası yazarı Naci Kasım'ın tercüme ettiği, Yusuf oğlu Ayas Bey'in 1385'te oğlu Sinan Bey adına düzenlediği vakfiyeden anlaşılmaktadır; Sinan Bey ile Hamza Bey'in kardeş olduğu ve her ikisinin de bu türbede medfun bulunduğu vakfiyeye göre kesindir. Caminin giriş kapısı üzerindeki üç satırlık kitabede caminin 1899-1900 (1317 H.) yılında yapıldığı, aşağıdaki manzum metinle birlikte kayıtlıdır:\n\n'Ne dikleş sürete girmiş binasu bu minarenin\nSanurmısın olur bihude mesai'si baninin\nMuhammed eyledi refik çünki hasbeden lillahtır sa'yi\n'Ve'l-bakiyatu's-salihat' dır müjdesi anın\nAtayi hakkı ile tarihin didin 'abd-i muhtar'\nAranur ise bilinsün vakt-i inşası bunun 1317'\n\nCaminin tamamı yenilenmiş olup tarihi bir özellik taşımamakla birlikte minaresi orijinaldir; kare kaideli, yuvarlak gövdeli ve tek şerefelidir. Caminin yanında Hamza Bin Ayas Bey'in türbesi de bulunmaktadır. Köy, Cumhuriyet döneminde 'Ayas' yerine 'Ayaz' adını almıştır; eskiden bataklık olan araziler 1965 sonrasında yapılan setlerle tarıma kazandırılmış, bugün köy sebze ve özellikle meyve üretimiyle öne çıkmaktadır." },
      "golyazi-eski-camii": { period: "Yapım tarihi kesin olarak bilinmiyor", founder: "Bilinmiyor", info: "Nilüfer ilçesine bağlı Gölyazı Köyü'nde bulunan cami büyük ölçüde yenilenmiştir. Doğu-batı yönünde dikdörtgen planlı yapının üzeri kiremit kaplı bir çatıyla örtülüdür; büyük yığma ve kesme taştan inşa edilmiştir. Minaresi tek şerefeli olup şerefe altı işlemelidir. Mihrap üstü pencerelerinden ikisi vitraylıdır. Son dönemde restorasyon gören caminin mihrabı kalem işi süsleme ve ayet işlemeleriyle bezelidir; minber ve kürsü ile kadınlar mahfili ahşap malzemeden yapılmıştır. Caminin hemen arkasında yıkık vaziyette bir sıbyan mektebi bulunur. Cami halen ibadete açıktır. Kaynak: Erol Şaşmaz" },
      "seyh-kutbuddin": { period: "Cami: iddiaya göre 1496; türbe daha erken (Şeyh Kutbuddin öl. 1418); cami 2004'te yeniden inşa edildi", founder: "Cami için Çandarlı İbrahim Paşa (öl. 1427) veya rivayete göre İbrahim Paşa (1496); türbe için Halil Paşa rivayeti de vardır", info: "Yeşil Camii ve Nilüfer Hatun İmareti'nin yanında yer alır; adını, bitişiğindeki Şeyh Kutbuddin'e (öl. 1418) ait türbeden alır. Cami, Çandarlı İbrahim Paşa tarafından yaptırıldığı kabul edilir; eskiden son cemaat yeri ve kubbeli kare bir mekândan ibaretti. Kare planlı, pandantif kubbeli türbenin girişi doğu duvarda, eksenin güneyinde yer alır; kuzey, güney ve batı duvarlarında eksende, doğu duvarında ise eksenin güneyinde birer pencere bulunur; içeride güneydeki pencereye simetrik iki dikdörtgen niş vardır. Türbeyi örten kubbe, üzeri kiremit kaplı sağır on iki köşeli bir kasnak üzerinde yükselir. Cami ve türbenin banisi konusunda kesin bir bilgi olmayıp, caminin İbrahim Paşa tarafından 1496'da, türbenin ise Halil Paşa tarafından yaptırıldığı öne sürülmektedir. Kare planlı cami ile ona bitişik, kuzeybatıda yer alan kare planlı türbe aynı eksendedir. Orijinal cami yıkılmış olup 2004 yılında aslına uygun şekilde yeniden inşa edilmiştir. Kurtuluş Savaşı sırasında Yunanlılar tarafından yakılıp yıkılan camilerden biridir; kapı, duvarları ve şerefesi yıkık vaziyette ayaktadır, minaresi tuğladandır. Üstü kubbeli, dört köşeli bir yapı olan türbe ise ilk Osmanlı dönemi duvar tekniğini yansıtmaktadır." },
      "karacabey-yenisaribeykoyu-camii": { period: "1954 (kitabesine göre)", founder: "Bilinmiyor", info: "Karacabey ilçesinin güneybatısında yan yana Sarıbey adlı üç köy bulunur: Eskisarıbey, Ortasarıbey ve en batıdaki Yenisarıbey. Yenisarıbey, eski Kokona adlı yerleşim yerinde kurulduğu için bu adla da anılmıştır; 1895 Yıllığı'na göre 42 haneli köyün diğer adının Kokona olduğu kayıtlıdır. 1934 yılına kadar Mustafakemalpaşa'ya bağlı olan köy, bu tarihte alınan bir kararla Karacabey'e bağlanmıştır. Eski bir Rum köyü olan Yenisarıbey'de 1927'de 271, 1997'de ise 523 kişi yaşamış; köyde 1880'li yıllarda gelen Bulgaristan göçmenleri ile 1897'de Yunanistan'ın Mora Yenişehir'inden gelen göçmenler iskân edilmiştir. Kitabesine göre 1954 yapımı olan cami dikdörtgen planlı olup kırma çatılı ve kiremit kaplıdır; çatı altı kaplaması ahşaptandır. Minaresi tek şerefeli olup şerefe altı işlemelidir. Cami duvarları ile mihrap, minber ve kürsü farklı desenli seramik/fayans kaplıdır. Müezzin mahfili ile kadınlar mahfili sade bir ahşap işçilikle yapılmıştır. Kaynak: Bursa Gazeteciler Cemiyeti (BGC) internet sitesi" },
      "karacabey-kumbetli-camii": { period: "Kesin yapım tarihi bilinmiyor; rivayete göre yaklaşık 2200 yıllık bir yapı olup yaklaşık bin yıldır cami olarak kullanılmaktadır", founder: "Bilinmiyor", info: "Karacabey ilçe merkezinde, Hamidiye Mahallesi'nde yer alan eski bir camidir; 'Dümbekli Mescidi' veya 'Tümbekli Cami' adlarıyla da anılır. Adını, yapının üzerindeki yarım küre biçimli tepe kısmından aldığı söylenir. Rivayete göre M.Ö. 200 yıllarında önce Yahudilere havra olarak ibadete açılan bina, daha sonra Hristiyanlara kilise, son olarak da cami olarak hizmet vermiştir; yapı üzerinde sekiz kollu şamdan ve Davud yıldızı izlerinin bulunduğu belirtilir. Bu özelliğiyle Musevilik, Hristiyanlık ve Müslümanlığın kesiştiği, Bursa'da bu niteliği taşıyan tek ibadethane olarak kabul edilir ve Karacabey'in en eski tarihi eseri sayılır. Doğu-batı yönünde dikdörtgen planlı harim, kuzeyinde ona bitişik bir yan mekân ve batısında son cemaat yerinden oluşur. Duvarların yapımında moloz taş ve mermer parçalarının yanı sıra Bizans dönemine ait sütun başlıklarından da yararlanılmıştır. Harim, eksenin batısında iki sütunlu, üç açıklıklı bir arkadla iki bölüme ayrılır; ortadaki açıklık sivri, yanlardaki açıklıklar yuvarlak kemerlidir. Kuzey-güney doğrultusunda dikdörtgen planlı batı bölüm beşik tonozla örtülüdür; batı duvardaki eksen kapısı son cemaat yerine, kuzey duvardaki basık kemerli kapı ise yan mekâna açılır, güney duvar ise sağırdır. Harimin kare planlı doğu bölümü, üçgen kuşakla geçilen bir kubbeyle örtülüdür; güney duvarında eksende yarım yuvarlak bir mihrap nişi ile iki yanında simetrik iki pencere bulunur. Kuzey-güney doğrultusunda dikdörtgen planlı son cemaat yerinde güney duvarda eksenin batısında bir pencere, batı duvar ekseninde giriş kapısı ve iki yanında ikişer pencere yer alır. Kuzeybatıdaki minaresi yuvarlak gövdeli, tek şerefeli ve konik külahlıdır. Kaynak: Kültür Portalı" },
      "karacabey-ismetpasa-haci-ali-aga-camii": { period: "1230 H. (1815) — kuzeydeki giriş kapısı üzerindeki 32x60 cm ölçülerindeki kitabeye göre", founder: "Kelisanlı Hacı Ali Ağa", info: "Karacabey'e bağlı İsmetpaşa köyünde bulunan cami, günümüzde kullanılmamakta olup harap durumdadır ve halen depo olarak kullanılmaktadır. Kuzey-güney doğrultusunda dikdörtgen planlı ve düz tavanlı yapıya, kuzey cephe eksenindeki kapıdan girilir; kapının iki yanında birer pencere bulunur. Güney duvar ekseninde yarım yuvarlak mihrap ile iki yanında birer pencere, doğu ve batı duvarlarda ise ikişer pencere yer alır. Harim ekseninde, ahşap tavanı taşıyan kare kesitli destekler mekânı ikiye ayırır. Harime giriş kapısı dikdörtgen, cephelerdeki pencereler yuvarlak kemerli olup pencerelerin üzerinde basık hafifletme kemerleri bulunur. Yapı kırma çatı ile örtülüdür; köşelerde ve kuzeybatıdaki minare kaidesinde kesme taş, beden duvarlarında ise moloz taş malzeme kullanılmıştır. Pencere kemerleri ile minare gövdesi tuğladandır. Kaynak: Kültür Portalı" },
      "karacabey-uluabat-eski-valide-sultan-camii": { period: "Yapı özellikleri ve rivayetlere göre 14. yüzyıl sonu - 15. yüzyıl başı (yöre halkına göre Bursa Ulu Camii'den sekiz yıl sonra, yaklaşık 1408); 1953'te kapsamlı onarım görmüştür", founder: "Kesin olarak bilinmiyor", info: "Karacabey ilçesine bağlı Uluabat köyünde bulunan cami, halk arasında 'Yıldırım Camii' veya 'Eski Cami' adlarıyla da bilinir. Yapı özellikleri ve adları dolayısıyla 14. yüzyıl sonu - 15. yüzyıl başında inşa edildiği düşünülmekte; yöre halkı, caminin Bursa Ulu Camii'den sekiz yıl sonra, yaklaşık 1408'de yapıldığını söylemektedir. Yanında eskiden bir hamam ve bir hanın da bulunduğu belirtilir; bu üçlü yapılanma Osmanlı'nın ilk dönemlerinde uyguladığı yerleşim düzenine uygun düşmektedir. Fetih sırasında Lopadion Kalesi'nin ileri karakol niteliğinde bir direnek noktası olduğuna dair bilgiler de bu görüşü destekler niteliktedir. Genel olarak kuzey-güney doğrultusunda dikdörtgen planlı olan cami, güneyde kare planlı bir ana mekân ve kuzeyde doğu-batı doğrultusunda dikdörtgen planlı, sonradan eklenmiş bir son cemaat yerinden oluşur. Doğu cephesinin kuzey köşesinde, özgünlüğünü yitirmiş düzensiz planlı bir minare kaidesi yer alır. Tavan düz ve ahşap olup yapı dıştan yenilenmiş bir kırma çatıyla örtülüdür; yapı malzemeleri arasında antik parçalara da rastlanmaktadır. Minare kaidesinde düzgün kesilmiş taş, devşirme mermer parçalar ve tuğla; minare gövdesinde ise tuğla kullanılmıştır. 1953 yılında gerçekleştirilen onarımda yapı hemen tümüyle değişikliğe uğramıştır. Kaynak: Bursa Gazeteciler Cemiyeti" },
      "karacabey-imaret-kursunlu-camii": { period: "İnşasına 1446'da başlanmış; banisinin 1456'da Belgrat Savaşı'nda şehit düşmesi üzerine vasiyeti gereği ailesi tarafından Fatih Sultan Mehmet devrinde, 1457 yılında tamamlanmıştır", founder: "Rumeli Beylerbeyi Büyük Emir Abdullah oğlu Dayı Karaca Bey (vefatının ardından ailesi tarafından tamamlattırılmıştır)", info: "Selimiye Mahallesi'nde yer alan caminin mülkiyeti Vakıflar Genel Müdürlüğü'ne aittir. 1853 depreminde hasar gören yapı, sonraki dönemde Yunanlılar tarafından da tahrip edilmiş; kullanılamaz hale gelen bina 1971-72 yıllarında Vakıflar Genel Müdürlüğü'nce onarılarak 12 Temmuz 1980'de yeniden ibadete açılmıştır. Kuzeyindeki imaret günümüze ulaşamamıştır. Caminin 36 penceresi, 9 kubbesi ve iki kapılı bir minaresi bulunur; son cemaat yeri ile kuzey-güney doğrultusunda art arda sıralanan giriş ve ibadet mekânından, girişin doğu ve batısında önlerinde birer dehliz bulunan iki yan kanattan oluşur. Doğu-batı yönünde dikdörtgen planlı son cemaat yeri, haçvari altı destek ve kemerle beş bölüme ayrılır; kuzey cephe, eş yükseklikteki sivri kemerli revakla dışa açılır. Kubbeler ve tonoz aynı yükseklikte olup kubbenin ortasında sekiz cepheli bir aydınlık feneri yükselir. Son cemaat yerinin güney duvarı ortasındaki giriş, malzeme çeşitliliği ile taş ve mermer işçiliğinin kalitesiyle dikkat çeker. Kübik kaideli, silindirik gövdeli, tek şerefeli ve piramidal külahlı minaresiyle yapının tamamı taştandır. Son cemaat revakının minare çevresindeki kubbesi altında Karaca Bey'in mezarı bulunur; kitabesinde, Belgrat Kalesi muharebelerinde şehit düşen Abdullah oğlu büyük emir Karaca Bey'in kabri olduğu yazılıdır. Tarihi kayıtlarda 'Kurşunlu Cami' adıyla da anılmaktadır. Kaynak: Bursa'nın Değerleri" },
      "karacabey-ulu-camii": { period: "I. Murad Hüdavendigar dönemi (1362-1389) vakfı; 1774'te (1188 H.) kapsamlı bir düzenleme ve muhtemelen I. Abdülhamit devrinde (1774-1789) bir onarım geçirmiş; Vakıflar Genel Müdürlüğü'nce 1964'te restore edilmiştir", founder: "I. Murad Hüdavendigar", info: "Şehrin 'Eski Karacabey' olarak anılan bölümünde yer alan cami, Osmanlı Sultanı I. Murad Hüdavendigar zamanında Bursa'da inşa edilen eserler arasında sayılır ve yapının onun vakfı olduğu kitabesinden anlaşılmaktadır; kitabede caminin sağlam bir yapı olduğu, çevresinde bir benzerinin bulunmadığı ve banisinin ve yapının kalıcılığına dair bir dua yer alır. 1774 yılında camiye ser-mahfil, muarrif, vaiz, müezzin, mütevelli, devirhan ve cüzühan gibi görevlendirmeler yapılmıştır. Depremler ve Kurtuluş Savaşı yıllarındaki Karacabey Yangını'nda ağır hasar gören eser, geçirdiği her onarımda özgün mimari özelliklerinden bir kısmını kaybetmiştir; günümüzde kubbesiz, çatılı bir görünüme sahiptir. Altıgen kaideli minaresi on altı kenarlı gövdeye sahip olup tek şerefelidir. Mimari veriler, yapının I. Abdülhamit döneminde (1774-1789) bir onarımdan geçtiğine işaret etmektedir. Yunan işgali sırasında yanan cami, Vakıflar Genel Müdürlüğü tarafından 1964 yılında restore edilmiş olup halen ibadete açıktır. Caminin harimi 19,34 x 16,60 m ölçülerinde ve çatılıdır. Yapının özgün haline kavuşturulması amacıyla hazırlanan yeni bir onarım ve restorasyon projesinin ilerleyen dönemde uygulamaya konması beklenmektedir. Kaynak: Kültür Varlıkları" }
    };
    // Kullanıcının cami bilgi kartında yaptığı düzenlemeler / sıfırlamalar (yalnızca bu cihazda saklanır)
    let MOSQUE_INFO_OVERRIDES = {};
    function loadMosqueInfoOverrides() {
      const raw = localStorage.getItem('manevi-atlas-mosque-info-overrides');
      if (!raw) return;
      try { MOSQUE_INFO_OVERRIDES = JSON.parse(raw) || {}; } catch (e) { MOSQUE_INFO_OVERRIDES = {}; }
    }
    function saveMosqueInfoOverrides() {
      localStorage.setItem('manevi-atlas-mosque-info-overrides', JSON.stringify(MOSQUE_INFO_OVERRIDES));
    }
    // Bellekteki veya localStorage'daki yeni eklenen camileri yüklemek için fonksiyon
    function loadCustomAddedMosques() {
      PRESET_MOSQUES.forEach(m => { if (m.isCustom === undefined) m.isCustom = false; });

      const savedCustom = localStorage.getItem('manevi-atlas-custom-mosques');
      if (savedCustom) {
        try {
          const list = JSON.parse(savedCustom);
          list.forEach(customMosque => {
            customMosque.isCustom = true;
            if (!PRESET_MOSQUES.some(m => m.id === customMosque.id)) {
              PRESET_MOSQUES.push(customMosque);
            }
          });
        } catch (e) {
          console.error("Özel cami listesi yüklenemedi", e);
        }
      }

      applyMosqueOverrides();

      const deletedRaw = localStorage.getItem('manevi-atlas-deleted-presets');
      if (deletedRaw) {
        try {
          const deletedIds = new Set(JSON.parse(deletedRaw).map(d => d.id));
          PRESET_MOSQUES = PRESET_MOSQUES.filter(m => !deletedIds.has(m.id));
        } catch (e) {
          console.error("Silinen cami listesi okunamadı", e);
        }
      }
    }
    // === CAMİ DÜZENLEME / SİLME / GERİ GETİRME YÖNETİMİ ===
    function persistCustomMosqueList() {
      const customList = PRESET_MOSQUES.filter(m => m.isCustom);
      localStorage.setItem('manevi-atlas-custom-mosques', JSON.stringify(customList));
    }
    function saveMosqueOverride(id, data) {
      let overrides = {};
      const raw = localStorage.getItem('manevi-atlas-mosque-overrides');
      if (raw) { try { overrides = JSON.parse(raw); } catch (e) {} }
      overrides[id] = data;
      localStorage.setItem('manevi-atlas-mosque-overrides', JSON.stringify(overrides));
    }
    function applyMosqueOverrides() {
      const raw = localStorage.getItem('manevi-atlas-mosque-overrides');
      if (!raw) return;
      try {
        const overrides = JSON.parse(raw);
        Object.keys(overrides).forEach(id => {
          const m = PRESET_MOSQUES.find(x => x.id === id);
          if (m) Object.assign(m, overrides[id]);
        });
      } catch (e) {
        console.error("Cami düzenlemeleri okunamadı", e);
      }
    }
    function getDeletedPresetMosques() {
      const raw = localStorage.getItem('manevi-atlas-deleted-presets');
      if (!raw) return [];
      try { return JSON.parse(raw); } catch (e) { return []; }
    }
    function updateDeletedMosquesCount() {
      const badge = document.getElementById('deletedMosquesCountBadge');
      if (badge) badge.textContent = getDeletedPresetMosques().length;
    }
    const DISTRICT_CODE = { "Osmangazi": "OSG", "Yıldırım": "YLD" };
    function getSicilNo(mosque) {
      const sameDistrict = PRESET_MOSQUES.filter(m => m.district === mosque.district);
      const idx = sameDistrict.findIndex(m => m.id === mosque.id) + 1;
      return `${DISTRICT_CODE[mosque.district] || 'DLT'}-${String(idx > 0 ? idx : sameDistrict.length + 1).padStart(2, '0')}`;
    }
